# 第02回 Python入門（解答コード）

上のセルから順に実行する．セルを書き換えたら，そのセルを実行し直すこと．

## Pythonに計算させてみよう

In [1]:
1+1

2

In [2]:
5-3

2

In [3]:
3 * 4

12

In [4]:
4 / 2

2.0

In [5]:
2 / 4

0.5

In [6]:
2 ** 8

256

In [7]:
10 % 3

1

In [8]:
10 // 3

3

## 文字列を扱おう

In [9]:
"Hello World"

'Hello World'

In [10]:
'Hello World'

'Hello World'

In [11]:
print("Hello World")

Hello World


In [12]:
print('Hello World')

Hello World


In [13]:
print(3)

3


## 変数に代入しよう

`=` を使うことで変数に値を代入できる．実数や文字列だって代入できる．

In [14]:
x = 1 + 1

In [15]:
print(x)

2


## なお，一つのセルに複数行命令を書いていい．

In [16]:
x = 7.2 / 1.8
print(x)

4.0


In [17]:
name = "ToshitakaMatsuki"
print(name)

ToshitakaMatsuki


## 変数を使った計算に慣れよう

In [19]:
x = 2
y = 5
z = 3 * x + 2 * y
print(z)

16


In [20]:
first_name = "Toshitaka"
last_name = "Matsuki"
full_name = first_name + " " + last_name
print(full_name)

Toshitaka Matsuki


## 予約語について

予約語（`if`, `for`, `class`, `def` など）はPythonの仕様ですでに使っているので，変数名などに使ってはいけない．
使うと `SyntaxError` になる．（`class_name` のように一部に使うのは構わない．）

In [21]:
if = 1

SyntaxError: invalid syntax (535306765.py, line 1)

In [22]:
class_name = 1   # 予約語を一部に使うのはOK
print(class_name)

1


## 複数のものをprint()に入れてもいい

`print(〇〇, 〇〇, 〇〇)` のように「,」で区切って何個でも並べることができる．

In [23]:
x = "おにぎり"
y = 2
print(x, y, "個")

おにぎり 2 個


## 累算代入文

変数を使った計算結果を同じ変数に代入する．`x = x + 1` と `x += 1` は同じ．
`+=`, `-=`, `*=`, `/=`, `**=`, `%=`, `//=` がある．

In [24]:
x = 1
x = x + 1
print(x)

2


In [25]:
x = 1
x += 1
print(x)

2


In [26]:
x = 10
x -= 3
print(x)
x *= 2
print(x)
x /= 7
print(x)
x **= 3
print(x)
x %= 5
print(x)
x //= 2
print(x)

7
14
2.0
8.0
3.0
1.0


## オブジェクト（データのこと）

`1` や `3` といったオブジェクトがコンピュータのメモリに格納されている．
変数に代入するとは，オブジェクトが格納された場所に名前（`x`）をつけること．

In [27]:
1

1

In [28]:
1+2

3

In [29]:
x = 1 + 2

In [30]:
print(x)

3


## 変数の中身は何度でも書き換え可能

In [31]:
x = 1
print(x)
x = 3
print(x)

1
3


## Pythonで扱うオブジェクトには色々な型がある

| 型 | 例 | 説明 |
|---|---|---|
| int型 | `1`, `3`, `5` | 整数のデータ |
| float型 | `1.2`, `4.3333..`, `300.834` | 浮動小数点数のデータ |
| bool型 | `True`, `False` | 真か偽のデータ |
| リスト | `[3, 8, 12, ...]` | データの集まり |
| 文字列型 | `"car"`, `"apple"` | 文字列のデータ |

これ以外にもたくさんある．`type()` 関数で型を調べられる．

In [32]:
print(type(1))
print(type(1.2))
print(type(True))
print(type([3, 8, 12]))
print(type("car"))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'list'>
<class 'str'>


## 整数(int型オブジェクト)を使って計算する

変数名は `_` を使ってわかりやすい名前をつける（`red_apple` は良い，`r_ap` は最悪）．

In [33]:
red_apple = 100
green_apple = 150

red_apple * 3 + green_apple * 2

600

## 浮動小数点数(float型オブジェクト)の計算

変数に `0.0` のように小数点を含む値を代入すると，浮動小数点数型(float型オブジェクト)の値になる．
計算機は無限の精度では計算できない（整数のint型ならそういう心配をしなくていい）．

In [34]:
time_hour = 3.5
travel_distance = 224.5
average_velocity = travel_distance / time_hour
print(average_velocity)

64.14285714285714


In [35]:
0.1+0.1+0.1

0.30000000000000004

## bool型は真か偽かを扱うオブジェクト

| 演算子 | 意味 |
|---|---|
| `<` | ＜ |
| `<=` | ≦ |
| `>` | ＞ |
| `>=` | ≧ |
| `!=` | ≠ |
| `==` | ＝ |

In [36]:
1 == 2

False

In [37]:
num1 = 10
num2 = 10
print(num1 == num2)

True


In [38]:
# 色々な比較を試してみよう
print(3 < 5)
print(3 <= 3)
print(3 > 5)
print(3 >= 5)
print(3 != 5)
print("abc" == "abc")
print("abc" == "abd")
print(2.0 == 2)

True
True
False
False
True
True
False
True


## list型(リスト型)はオブジェクトの集まり

中の値の型は同じでなくてもいい．リストの中にリストなんてこともOK．
中身を参照したい時は `[ ]` をつけて何番目かを指定する（0から始まることに注意，インデキシングという）．

In [39]:
list1 = [1, 2, 3]
print(list1)

[1, 2, 3]


In [40]:
list2 = [1, "a", False, 3.14]
print(list2)

[1, 'a', False, 3.14]


In [41]:
list3 = [list1, list2]
print(list3)

[[1, 2, 3], [1, 'a', False, 3.14]]


In [42]:
print(list1[0])
print(list1[2])

1
3


## string型(文字列型)は文字を扱う

`I'm Toshitaka Matsuki` のように，文章中で `'` を使いたい場合は `"` で囲む（そうしないとエラー）．
文字列同士を足し算したりもできる．

In [43]:
print("Hello")
print('Hello')
print("I'm Toshitaka Matsuki.")

Hello
Hello
I'm Toshitaka Matsuki.


In [44]:
print('I'm Toshitaka Matsuki')

SyntaxError: unterminated string literal (detected at line 1) (2818055.py, line 1)

In [45]:
first_name = "Toshitaka"
last_name = "Matsuki"
full_name = first_name + last_name
print(full_name)

ToshitakaMatsuki


## 関数

様々な処理の集まり．値をもらったり（引数）返したり（戻り値）することもある．

- `len()` : 引数の長さを返す
- `help()` : Pythonのヘルプを起動する（引数なしで実行すると対話型ヘルプが起動し，`quit` で終了する．ここでは `help(len)` のように調べたいものを渡して使う）
- `str()` : 引数の型を文字列型に変換したものを返す

In [46]:
list1 = [1, 2, 3, 4, 5, 6]
len(list1)

6

In [47]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [48]:
str(1)

'1'

## input()を使って入力を受け付ける

- `input()` でユーザーからのキーボード入力を受け付けることができる．
- 引数に文字列を入れると，入力受付時に表示される．
- 入力された値は **文字列型** として返ってくる．

In [49]:
key_input = input('何か打ち込んでください. :')
print(key_input)

何か打ち込んでください. :こんにちは
こんにちは


## 課題1

> ユーザーに $x$ と $y$ の値を入力してもらうように問いかけて，$x^3 + xy - y^2$ を計算し，
> 「xの三乗 たす xy ひく yの二乗 は〇〇です.」と表示するプログラムを書いて見ましょう．(〇〇は計算結果)

### 解答例

`input()` が返すのは文字列なので，`int()` で整数に変換してから計算する．

In [50]:
x = int(input('xの値を入力してください: '))
y = int(input('yの値を入力してください: '))

answer = x ** 3 + x * y - y ** 2
print('xの三乗 たす xy ひく yの二乗 は', answer, 'です.')

xの値を入力してください: 3
yの値を入力してください: 2
xの三乗 たす xy ひく yの二乗 は 29 です.


> ユーザーに，$x=3$, $y=2$ のとき，xの三乗 たす xy ひく yの二乗は？ と問いかけて，打ち込まれた値が
> 正しければ，「あなたの答え〇〇はTrueです.」(〇〇は計算結果)
> 間違ってたら，「あなたの答え〇〇はFalseです.」と表示するプログラムを書いて見ましょう．(ifは使わない)

### 解答例

比較演算子 `==` の結果（bool型）をそのまま `print()` に渡せばよい．

In [51]:
x = 3
y = 2
correct_answer = x ** 3 + x * y - y ** 2

user_answer = int(input('x = 3, y = 2のとき, xの三乗 たす xy ひく yの二乗は? :'))
print('あなたの答え', user_answer, 'は', user_answer == correct_answer, 'です.')

x = 3, y = 2のとき, xの三乗 たす xy ひく yの二乗は? :29
あなたの答え 29 は True です.


## メソッド

それぞれのデータ型が固有にもつ関数を **メソッド** という．`<オブジェクト>.<メソッド名>()` のように使う．

- `<文字列型>.split(〜)` : 〜で区切ってリストに格納して返す
- `<文字列型>.upper()` : 全てのアルファベットを大文字にして返す

メソッドによる編集を残したい場合は変数に代入する．

In [52]:
address = 'Dannoharu,Oita,Japan'

In [53]:
address.split(',')

['Dannoharu', 'Oita', 'Japan']

In [54]:
address.upper()

'DANNOHARU,OITA,JAPAN'

In [55]:
print(address)
upper_address = address.upper()
print(upper_address)

Dannoharu,Oita,Japan
DANNOHARU,OITA,JAPAN


## モジュール

モジュール（Pythonのプログラム）はデータ型（クラス）や関数を持っていて，データ型は変数（属性）やメソッドを持っている．
`import` することで自作プログラムから使えるようになる．

### datetimeモジュールを使ってみよう！

`birth_day = datetime.date(1988, 5, 6)` で，datetimeモジュールが持っている date型のデータ（インスタンス）を作る．

In [56]:
import datetime

birth_day = datetime.date(1988, 5, 6)
print(birth_day)
print(type(birth_day))

1988-05-06
<class 'datetime.date'>


## date型のメソッドを使ってみよう！

- date型 : `year`, `month`, `day` の変数と，`today()`, `replace()`, `weekday()` などのメソッドを持つ
- timedelta型 : `days`, `seconds`, `microseconds` の変数を持つ（日付の差や，日付に足す「期間」を表す）

In [57]:
import datetime

In [58]:
birthday = datetime.date(1988, 5, 6)
today = datetime.date.today()
print(birthday)   # 誕生日
print(today)      # 今日の日付

1988-05-06
2026-10-08


In [59]:
print(today - birthday)   # 生まれてから何日経ったか

14034 days, 0:00:00


In [60]:
print(birthday.weekday())   # 誕生日の曜日 (月曜〜日曜 が 0〜6)
print(today.weekday())      # 今日の曜日

4
3


In [61]:
tomorrow = today + datetime.timedelta(days=1)    # 今日 + 1日
print(tomorrow)
yesterday = today + datetime.timedelta(days=-1)  # 今日 + (-1日)
print(yesterday)

2026-10-09
2026-10-07


In [62]:
this_birthday = birthday.replace(year=today.year)   # 今年の誕生日 (スライドでは year=2019)
print(this_birthday - today)                        # 今年の誕生日まであと何日か (過ぎていれば負の値になる)

-155 days, 0:00:00


## mathモジュール

`sqrt` => **sq**uare **r**oo**t**（平方根）．`help(math)` とすれば他にもたくさんの機能があることがわかる．

In [63]:
import math

sqrt_value = math.sqrt(36)
print(sqrt_value)

log_value = math.log2(10)
print(log_value)

6.0
3.321928094887362


In [64]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

## ライブラリ

複数のモジュールをまとめたものが **ライブラリ**．ライブラリが超充実しているところもPythonの大きな魅力（100万個ぐらいあるらしい）．

| ライブラリ | 用途 |
|---|---|
| Numpy | 数値計算処理 |
| Pandas | 統計データ解析 |
| matplotlib | グラフ描写 |
| pytorch / Tensor Flow | Deep learning |
| Scipy | 科学技術計算 |
| pygame / pyxel | ゲーム作成 |

全てのライブラリはPyPIというサービスで管理されていて，`pip` コマンドでインストールできる．

## 課題2

> ユーザーに誕生日を入力してもらうように問いかけて，
> 「あなたが生まれてから〇〇日たちました.」
> 「あなたが生まれてから〇〇年たちました.」
> と表示するプログラムを書いて見ましょう．(〇〇は計算結果)

### 解答例

In [65]:
import datetime

year = int(input('生まれた年(西暦)を入力してください: '))
month = int(input('生まれた月を入力してください: '))
day = int(input('生まれた日を入力してください: '))

birthday = datetime.date(year, month, day)
today = datetime.date.today()
passed = today - birthday          # timedelta型

print('あなたが生まれてから', passed.days, '日たちました.')
print('あなたが生まれてから', passed.days // 365, '年たちました.')   # うるう年を無視した概算

生まれた年(西暦)を入力してください: 1988
生まれた月を入力してください: 5
生まれた日を入力してください: 6
あなたが生まれてから 14034 日たちました.
あなたが生まれてから 38 年たちました.


> ユーザーに何日後の曜日が知りたいですかと問いかけて，
> 「〇〇日後は□年×月△日〜曜日です」(曜日は数字でいい)
> と表示するプログラムを書きましょう

### 解答例

In [66]:
import datetime

n = int(input('何日後の曜日が知りたいですか?: '))

today = datetime.date.today()
target_day = today + datetime.timedelta(days=n)

print(n, '日後は', target_day.year, '年', target_day.month, '月', target_day.day, '日',
      target_day.weekday(), '曜日です')

# おまけ: リストを使えば曜日を文字にできる (weekday()は 月曜=0, ..., 日曜=6)
youbi = ['月', '火', '水', '木', '金', '土', '日']
print(n, '日後は', target_day.year, '年', target_day.month, '月', target_day.day, '日',
      youbi[target_day.weekday()], '曜日です')

何日後の曜日が知りたいですか?: 100
100 日後は 2027 年 1 月 16 日 5 曜日です
100 日後は 2027 年 1 月 16 日 土 曜日です


## 演算子をしっかり使いこなそう

一行一行！打つべし打つべし！どんな結果が出る？

In [67]:
print(2 + 2)
print(5 - 2)
print(5 * 6)
print(50 - 5 * 6)
print((50 - 5) * 6)
print(8 / 5)
print(type(1))
print(type(1.6))
print(0.6)
print(.6)
print(17 / 3)
print(17 // 3)
print(17 % 3)
print(5 * 5)
print(5 ** 2)
print(5 * 5 * 5 * 5 * 5)
print(5 ** 5)
x = 5
print(x)
y = 10
print(x * y)

4
3
30
20
270
1.6
<class 'int'>
<class 'float'>
0.6
0.6
5.666666666666667
5
2
25
25
3125
3125
5
50


## コードをたくさん書いて慣れよう

結局上達するにはたくさんコードを書いてみて慣れていくのが一番．一行一行実行して，何が起こるか確認してみよう．
（`int()` は整数に，`str()` は文字列に変換する関数．）

In [68]:
num = 10
name = "2019"
print("#######################")
print(num, name)
print(num, type(num))
print(name, type(name))
print("#######################")
num = name
print(num, type(num))
print("#######################")
num = int(name)
print(num, type(num))
print("#######################")
num = str(name)
print(num, type(num))

#######################
10 2019
10 <class 'int'>
2019 <class 'str'>
#######################
2019 <class 'str'>
#######################
2019 <class 'int'>
#######################
2019 <class 'str'>


## print()関数のあれこれ

- 引数を複数与えるとどうなる？
- `sep` というキーワード引数の意味は？（区切り文字．省略時は半角スペース）
- `end` というキーワード引数の意味は？（末尾につける文字．省略時は改行 `\n`）

In [69]:
print('Hi', 'Mike')

Hi Mike


In [70]:
print('Hi', 'Mike', sep=',')

Hi,Mike


In [71]:
print('Hi', 'Mike', sep=',')
print('Hi', 'Mike', sep=',')

Hi,Mike
Hi,Mike


In [72]:
print('Hi', 'Mike', sep=',', end=':')
print('Hi', 'Mike', sep=',', end=':')

Hi,Mike:Hi,Mike:

In [73]:
print('Hi', 'Mike', sep=',', end='.\n')
print('Hi', 'Mike', sep=',', end='.\n')

Hi,Mike.
Hi,Mike.


## 文字列をprintする時のあれこれ

- `"` でも `'` でもどっちでもよかった
- `\` はなんだと思う？（エスケープ文字．直後の文字の意味を変える）
- `\n` はなんだと思う？（改行）
- 文字列の前に `r` を入れると！！（raw文字列．`\` をそのままの文字として扱う）

In [74]:
print('hello')
print("hello")
print()
print("I don't know.")
print('I don\'t know.')
print()
print('Say "I don\'t know".')
print("Say \"I don't know\". ")
print()
print('Hello. \n How are you?')
print()
print('C:\name\name')
print(r'C:\name\name')

hello
hello

I don't know.
I don't know.

Say "I don't know".
Say "I don't know". 

Hello. 
 How are you?

C:
ame
ame
C:\name\name


`"""` で囲むと複数行の文字列が書ける．行末に `\` を入れると，その改行は無視される．

In [75]:
print('###')
print("""
line1
line2
line3
""")
print('###')

###

line1
line2
line3

###


In [76]:
print('###')
print("""line1
line2
line3""")
print('###')

###
line1
line2
line3
###


In [77]:
print('###')
print("""\
line1
line2
line3\
""")
print('###')

###
line1
line2
line3
###


文字列にも演算子が使える！！スペースを挟んで並べた文字列は合体する．長い文章はこう書けばコードが綺麗．

In [78]:
print('Hi.' * 3)
print('Hi.' * 3 + 'Mike.')
print('###')
print('Py' 'thon')
long_sentence = ('春はあけぼの。'
                 'やうやう白くなりゆく山ぎはすこしあかりて、'
                 'むらさきだちたる雲のほそくたなびきたる')
print(long_sentence)

Hi.Hi.Hi.
Hi.Hi.Hi.Mike.
###
Python
春はあけぼの。やうやう白くなりゆく山ぎはすこしあかりて、むらさきだちたる雲のほそくたなびきたる


## 課題3

> 以下の問いかけに対して説明してください
> - print()関数のsep引数はなんですか？どんな使い方が考えられますか？
> - print()関数のend引数はなんですか？どんな使い方が考えられますか？
> - 文字列の中に＼(もしくは¥)があるとどんな意味がありますか？どんな時に使うと考えれますか？
> - ＼n (もしくは¥n)はどんな意味ですか？
> - 文字列の前にrをつけるとなにが起きますか？

### 解答例

- **sep引数** : `print()` に複数の値を渡したときに，値と値の間に挟む区切り文字を指定する（省略時は半角スペース）．
  例えば `sep=','` とすればCSV形式の1行を作れるし，`sep=''` とすれば値をくっつけて表示できる．
- **end引数** : 表示の最後につける文字を指定する（省略時は改行 `\n`）．
  `end=''` や `end=' '` とすれば改行せずに次の `print()` の出力を同じ行に続けられるので，
  ループの中で進捗を横に並べて表示するときなどに使える．
- **＼（バックスラッシュ）** : エスケープ文字．直後の文字と組み合わせて特別な意味を持たせる．
  `\'` や `\"` のように「文字列を囲む記号そのものを文字として使いたい」時や，
  `\n`（改行）・`\t`（タブ）のように「キーボードから打ちにくい文字」を表したい時に使う．
  また，行末に置くと「次の行に続く」という意味になる．
- **＼n** : 改行を表す文字．文字列の途中に入れると，そこで行が変わる．
- **r** : raw文字列になり，`\` がエスケープ文字ではなく普通の文字として扱われる．
  `r'C:\name\name'` のようにWindowsのファイルパスや，正規表現を書くときに便利．

In [79]:
# sep: CSV形式で表示する
print('Oita', 'Kumamoto', 'Fukuoka', sep=',')
# end: 改行せずに横に並べる
print('1番目', end=' / ')
print('2番目', end=' / ')
print('3番目')
# \ : 囲み記号をそのまま使う, \n: 改行, \t: タブ
print('It\'s a pen.\n名前\t年齢')
# r: バックスラッシュをそのまま表示する
print(r'C:\new_folder\test.txt')

Oita,Kumamoto,Fukuoka
1番目 / 2番目 / 3番目
It's a pen.
名前	年齢
C:\new_folder\test.txt


## list型(リスト型)はオブジェクトの集まり

中の値の型は同じでなくてもいい！リストの中にリストなんてこともOK!

In [80]:
list_1 = [1, 2, 3]
print(list_1)

[1, 2, 3]


In [81]:
list_2 = [1, "a", False, 3.14]
print(list_2)

[1, 'a', False, 3.14]


In [82]:
list_3 = [list_1, list_2]
print(list_3)

[[1, 2, 3], [1, 'a', False, 3.14]]


## リスト型のインデキシング

- `[i]` → $i$ 番目を取得（0から数える．負の数は後ろから数える）
- `[i:j]` → $i$ 番目から $j-1$ 番目を取得

In [83]:
N = [6, 3, 1, 8, 0, 7]

In [84]:
N[0]

6

In [85]:
N[3]

8

In [86]:
N[-1]

7

In [87]:
N[-2]

0

In [88]:
N[0:2]

[6, 3]

## リスト型のスライシング

- `[:j]` → 始端から $j-1$ 番目までを取得
- `[i:]` → $i$ 番目から終端までを取得
- `[i:j:s]` → $i$ 番目から $j-1$ 番目までを $s$ 個ずつ飛ばして取得（$s<0$ のとき逆順）

In [89]:
N = [6, 3, 1, 8, 0, 7]
print(N[:3])
print(N[2:])
print(N[:])
print(N[2:5])
print(N[::2])
print(N[::-1])

[6, 3, 1]
[1, 8, 0, 7]
[6, 3, 1, 8, 0, 7]
[1, 8, 0]
[6, 1, 0]
[7, 0, 8, 1, 3, 6]


## ネスト構造 〜リストの中のリスト〜

要素を取得するには `[〇][●]` のようにする（外堀から埋めるイメージ）．

In [90]:
abc = ['a', 'b', 'c']
num = [1, 2, 3]
nest = [abc, num]
print(nest)

[['a', 'b', 'c'], [1, 2, 3]]


In [91]:
print(nest[0])

['a', 'b', 'c']


In [92]:
print(nest[0][1])

b


In [93]:
print(nest[1][2])

3


## リストの要素を書き換える

リストの中身を参照して書き換えることも可能．スライスして書き換えたりもできる！スライスして `[]` に書き換えるとなくなる．

In [94]:
alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
alphabets[0] = 'A'
print(alphabets)

['A', 'b', 'c', 'd', 'e', 'f', 'g']


In [95]:
print(alphabets[2:5])
alphabets[2:5] = ['C', 'D', 'E']
print(alphabets)

['c', 'd', 'e']
['A', 'b', 'C', 'D', 'E', 'f', 'g']


In [96]:
alphabets[2:5] = []
print(alphabets)

['A', 'b', 'f', 'g']


## リスト型の関数とエラー

`len()` 関数で長さを測れる．`type()` 関数でlist型だとわかる．存在しない番号を指定すると `IndexError` になる．

In [97]:
N = [6, 3, 1, 8, 0, 7]
len(N)

6

In [98]:
type(N)

list

In [99]:
N[100]

IndexError: list index out of range

## リスト型に変換する list() 関数

`list()` 関数でシーケンス型（リスト型，集合型，レンジ型，文字列型など）のオブジェクトをリスト型に変換できる．

In [100]:
strings = 'abcdefg'
strings_list = list(strings)
print(strings)
print(strings_list)

abcdefg
['a', 'b', 'c', 'd', 'e', 'f', 'g']


## リストに掛け算をするとこうなる

リストに数値をかけるとその要素が増える．リストの要素が複数なら繰り返される．

In [101]:
L_zero3 = [0] * 5
print(L_zero3)

[0, 0, 0, 0, 0]


In [102]:
L_123_3 = [1, 2, 3] * 3
print(L_123_3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [103]:
L_123_3 = [[1, 2, 3]] * 4
print(L_123_3)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


## 課題4

> `L = [1,2,3,4,5,6,7,8,9,10]` というリストに対し，インデキシング・スライシングを使って，次のような処理をやってみてください．
> - 数字の3から7までを `L_3to7` に代入
> - Lを逆順にし，`L_reverse` に代入
> - Lから奇数だけ取り出し，`L_odd` に代入
> - Lから偶数だけ取り出し，`L_even` に代入 (小さい順)

### 解答例

In [104]:
L = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

L_3to7 = L[2:7]        # 3は2番目, 7は6番目 → [2:7]
L_reverse = L[::-1]    # ステップ -1 で逆順
L_odd = L[::2]         # 0番目から1つ飛ばし → 1, 3, 5, 7, 9
L_even = L[1::2]       # 1番目から1つ飛ばし → 2, 4, 6, 8, 10

print('L_3to7    =', L_3to7)
print('L_reverse =', L_reverse)
print('L_odd     =', L_odd)
print('L_even    =', L_even)

L_3to7    = [3, 4, 5, 6, 7]
L_reverse = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
L_odd     = [1, 3, 5, 7, 9]
L_even    = [2, 4, 6, 8, 10]


## リスト型のメソッド

- `append()` : 値を末尾に追加する
- `insert(〇, ●)` : 〇番目に●を挿入する
- `pop(〇)` : 〇番目の値を取り出す（リストからは消える）

In [105]:
N = [1, 2, 3, 4, 5]

In [106]:
N.append(100)
print(N)

[1, 2, 3, 4, 5, 100]


In [107]:
N.insert(0, 200)
print(N)

[200, 1, 2, 3, 4, 5, 100]


In [108]:
print(N.pop(0))
print(N)

200
[1, 2, 3, 4, 5, 100]


## リスト型のメソッド2

`remove()` メソッド : 指定した値を取り除く（最初に見つかった1つだけ）．中に無いものをremoveするとエラーになる！！

In [109]:
numbers = [3, 6, 7, 7, 7, 8, 9]
print(1, numbers)
numbers.remove(7)
print(2, numbers)
numbers.remove(7)
numbers.remove(7)
print(3, numbers)

1 [3, 6, 7, 7, 7, 8, 9]
2 [3, 6, 7, 7, 8, 9]
3 [3, 6, 8, 9]


In [110]:
numbers = [3, 6, 7, 8, 9]
numbers.remove(2)

ValueError: list.remove(x): x not in list

## リスト型の合体！！

リストとリストを `+` で足すと合体．`+=` でもオッケー．`extend()` メソッドでも合体できる．

In [111]:
a = [1, 2, 3]
b = [4, 5, 6]
x = a + b
print(x)

[1, 2, 3, 4, 5, 6]


In [112]:
a = [1, 2, 3]
b = [4, 5, 6]
a += b
print(a)

[1, 2, 3, 4, 5, 6]


In [113]:
a = [1, 2, 3]
b = [4, 5, 6]
a.extend(b)
print(a)

[1, 2, 3, 4, 5, 6]


## リストの検索

`index()` メソッドは値がある場所を返す（第二引数は検索の開始地点）．`in` を使えば値の有無がわかる．

In [114]:
N = [1, 2, 3, 4, 5, 1, 2, 3,
     1, 2, 3, 4, 5, 6, 7, 8, ]
print(N.index(3))
print(N.index(3, 3))
print(N.index(3, 8))

2
7
10


In [115]:
print(6 in N)
print(100 in N)

True
False


## リストの並び替え

`sort()` メソッドで並び替え．引数 `reverse` を `True` にすると反転ソート．
`reverse()` メソッドで中身を反転する（ソートはしないことに注意）．

In [116]:
N = [1, 2, 3, 1, 2,
     1, 2, 3, 4, 5, ]
print(N)

[1, 2, 3, 1, 2, 1, 2, 3, 4, 5]


In [117]:
N.sort()
print(N)

[1, 1, 1, 2, 2, 2, 3, 3, 4, 5]


In [118]:
N.sort(reverse=True)
print(N)

[5, 4, 3, 3, 2, 2, 2, 1, 1, 1]


In [119]:
N.reverse()
print(N)

[1, 1, 1, 2, 2, 2, 3, 3, 4, 5]


## rangeを使ったリストの作り方

`range()` を使うと，数列を扱うrange型のデータを作ることができる．`list()` を使ってリスト化！

- `range(i, j)` によって $i$ から $j-1$ までの数列になる
- `range(i, j, k)` によって $i$ から $j-1$ までで，$k$ 間隔の数列になる

In [120]:
L = list(range(5))
print(L)

[0, 1, 2, 3, 4]


In [121]:
L = list(range(3, 9))
print(L)

[3, 4, 5, 6, 7, 8]


In [122]:
L = list(range(3, 9, 2))
print(L)

[3, 5, 7]


## リストの検索とソート

helpのドキュメントも活用しましょう．

In [123]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

## 課題5

> `L = [2,4,6,8,10,12,14,16]` というリストをrange関数を利用して作り，次のような処理をやってみてください．
> - Lの末尾に18を追加する
> - Lの先頭を "取り出して" 変数xに代入する
> - Lから4を削除する
> - Lに対して[1,2,3]をappend()してみる．その結果がどうなったか，なぜそうなったか，extend()との違いにも触れながら説明してみる．

### 解答例

In [124]:
L = list(range(2, 17, 2))
print('作成したリスト:', L)

L.append(18)              # 末尾に18を追加
print('append(18)   :', L)

x = L.pop(0)              # 先頭を取り出してxに代入
print('pop(0)       :', L, ' x =', x)

L.remove(4)               # 4を削除
print('remove(4)    :', L)

L.append([1, 2, 3])       # [1,2,3]をappend
print('append([1,2,3]):', L)

作成したリスト: [2, 4, 6, 8, 10, 12, 14, 16]
append(18)   : [2, 4, 6, 8, 10, 12, 14, 16, 18]
pop(0)       : [4, 6, 8, 10, 12, 14, 16, 18]  x = 2
remove(4)    : [6, 8, 10, 12, 14, 16, 18]
append([1,2,3]): [6, 8, 10, 12, 14, 16, 18, [1, 2, 3]]


**説明** : `append()` は引数を「1つの要素」として末尾に追加するので，リスト `[1, 2, 3]` がまるごと1つの要素として入り，
`[6, 8, ..., 18, [1, 2, 3]]` のようなネスト構造になる（長さは1しか増えない）．
一方 `extend()` は引数のリストの「中身を1つずつ」末尾に追加するので，`[6, 8, ..., 18, 1, 2, 3]` となる（長さは3増える）．

In [125]:
L = list(range(2, 17, 2))
L.extend([1, 2, 3])       # extend()なら中身が1つずつ追加される
print('extend([1,2,3]):', L)
print('長さ:', len(L))

extend([1,2,3]): [2, 4, 6, 8, 10, 12, 14, 16, 1, 2, 3]
長さ: 11


> 100以下で3の倍数が入ったリストをrange関数を利用して作り，次のような処理をやってみてください．
> - ユーザーから3の倍数を入力してもらい，リストの中に存在すればTrue，無ければFalseと表示するプログラムを書く
>
> 次の手順でリストを作ってみてください
> - 1,2,3が10回繰り返されるリストを作り，そのリストをソートして `[1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3]` を作る．
>   また，逆順のパターン `[3,3,....2,2,....1,1]` も作ってみる

### 解答例

In [126]:
L = list(range(3, 101, 3))   # 3, 6, 9, ..., 99
print(L)

num = int(input('3の倍数を入力してください: '))
print(num in L)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
3の倍数を入力してください: 27
True


In [127]:
L = [1, 2, 3] * 10
print(L)

L.sort()
print(L)

L.sort(reverse=True)
print(L)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## リストのコピーの注意点

リスト `x` を作り `y` に代入してから `y[0]` を書き換えると，`x` の内容まで変化している！
（`y = x` は「同じリストに別の名前をつけた」だけで，コピーではない．）

In [128]:
x = [1, 2, 3]
y = x
print('x=', x)
print('y=', y)
y[0] = 100
print('x=', x)
print('y=', y)

x= [1, 2, 3]
y= [1, 2, 3]
x= [100, 2, 3]
y= [100, 2, 3]


## copy()メソッドを使うとよし

`y = x.copy()` とすれば別のリストが作られるので，`y` を書き換えても `x` は変わらない．

In [129]:
x = [1, 2, 3]
y = x.copy()
print('x=', x)
print('y=', y)
y[0] = 100
print('x=', x)
print('y=', y)

x= [1, 2, 3]
y= [1, 2, 3]
x= [1, 2, 3]
y= [100, 2, 3]


## リストの中にリストがあるとdeepcopy()が必要

`[[5, 8, 4], 2, 3]` みたいなとき，`copy()` では外側のリストしかコピーされない（内側のリストは共有されたまま）．
`copy` モジュールの `deepcopy()` を使うと中身まで全部コピーされる．「深いコピー」というワードだけ覚えておきましょう．
この「コピー」の件はPythonを使っているといつかぶつかると思うので頭の隅に入れておきましょう！！

In [130]:
import copy

x = [[5, 8, 4], 2, 3]
y = x.copy()            # 浅いコピー
y[0][0] = 100           # 内側のリストを書き換える
print('x=', x)          # xまで変わってしまう！
print('y=', y)

x= [[100, 8, 4], 2, 3]
y= [[100, 8, 4], 2, 3]


In [131]:
import copy

x = [[5, 8, 4], 2, 3]
y = copy.deepcopy(x)    # 深いコピー
y[0][0] = 100
print('x=', x)          # xは変わらない
print('y=', y)

x= [[5, 8, 4], 2, 3]
y= [[100, 8, 4], 2, 3]


## 課題6

> - 自分で好きなリストを作成し，リストのメソッドcopy()の意味がわかるプログラムを描いてみてください．(知らない人に説明するつもりで解説も合わせて示す)
> - 自分で好きなリストを作成し，リストのメソッドdeepcopy()の意味がわかるプログラムを描いてみてください．(知らない人に説明するつもりで解説も合わせて示す)

### 解答例（copy()）

リストを別の変数に `=` で代入しても，新しいリストが作られるわけではなく，
**同じリストに2つ目の名前（ラベル）が付くだけ** である．そのため片方を書き換えるともう片方も変わってしまう．
`copy()` メソッドは中身が同じ **別のリスト** を新しく作って返すので，コピー後は独立して書き換えられる．

In [132]:
fruits = ['apple', 'banana', 'cherry']

# (1) = で代入した場合: 同じリストに別の名前をつけただけ
same_fruits = fruits
same_fruits.append('durian')
print('fruits      :', fruits)         # fruitsにもdurianが入っている
print('same_fruits :', same_fruits)
print('同じオブジェクト?', fruits is same_fruits)

# (2) copy() を使った場合: 中身が同じ別のリストができる
copied_fruits = fruits.copy()
copied_fruits.append('elderberry')
print('fruits        :', fruits)       # fruitsは変わらない
print('copied_fruits :', copied_fruits)
print('同じオブジェクト?', fruits is copied_fruits)

fruits      : ['apple', 'banana', 'cherry', 'durian']
same_fruits : ['apple', 'banana', 'cherry', 'durian']
同じオブジェクト? True
fruits        : ['apple', 'banana', 'cherry', 'durian']
copied_fruits : ['apple', 'banana', 'cherry', 'durian', 'elderberry']
同じオブジェクト? False


### 解答例（deepcopy()）

`copy()` は「浅いコピー」で，外側のリストだけを新しく作り，中に入っているリスト（内側のリスト）は元のリストと **共有したまま** になる．
そのため内側のリストの要素を書き換えると，コピー元にも影響してしまう．
`copy` モジュールの `deepcopy()` は「深いコピー」で，内側のリストまで再帰的に全て新しく作るので，完全に独立したコピーになる．

In [133]:
import copy

# 生徒ごとの点数リスト (リストの中にリスト)
scores = [['Alice', 80, 90], ['Bob', 70, 60]]

# (1) copy(): 外側だけコピー, 内側のリストは共有される
shallow = scores.copy()
shallow[0][1] = 100               # 内側のリストを書き換える
print('scores  :', scores)        # 元のデータまで100になってしまった!
print('shallow :', shallow)
print('内側は同じオブジェクト?', scores[0] is shallow[0])

# (2) deepcopy(): 内側まで全部コピーされる
scores = [['Alice', 80, 90], ['Bob', 70, 60]]
deep = copy.deepcopy(scores)
deep[0][1] = 100
print('scores  :', scores)        # 元のデータは変わらない
print('deep    :', deep)
print('内側は同じオブジェクト?', scores[0] is deep[0])

scores  : [['Alice', 100, 90], ['Bob', 70, 60]]
shallow : [['Alice', 100, 90], ['Bob', 70, 60]]
内側は同じオブジェクト? True
scores  : [['Alice', 80, 90], ['Bob', 70, 60]]
deep    : [['Alice', 100, 90], ['Bob', 70, 60]]
内側は同じオブジェクト? False


## 文字列型（インデキシング・スライシング）

リストと同じように `[ ]` で文字を参照したり範囲を指定したりできる．

In [134]:
word = 'python'
print(word[0])
print(word[1])
print(word[-1])
print(word[-2])
print(word[2:5])
print(word[0:2])
print(word[:2])
print(word[2:])

p
y
n
o
tho
py
py
thon


文字列の要素を指定して書き換えることはできない（エラーになる）．どうしても置き換えたいなら新しい文字列を作る．文字列の長さは `len()` で測れる．

In [135]:
word[0] = 'j'

TypeError: 'str' object does not support item assignment

In [136]:
word = 'j' + word[1:]
print(word)

jython


In [137]:
length = len(word)
print(length)

6


## 文字列型のメソッド

文字列型のメソッドを使ってみよう．それぞれどんな機能だと思う？

In [138]:
sentence = 'My name is Mike. Hi Mike'
print(sentence)
is_start = sentence.startswith('My')
print(is_start)
is_start = sentence.startswith('X')
print(is_start)

My name is Mike. Hi Mike
True
False


In [139]:
print(sentence.find('Mike'))        # 最初に見つかった位置
print(sentence.rfind('Mike'))       # 最後に見つかった位置
print(sentence.count('Mike'))       # 出現回数
print(sentence.capitalize())        # 先頭だけ大文字
print(sentence.title())             # 単語の先頭を大文字
print(sentence.upper())             # 全て大文字
print(sentence.lower())             # 全て小文字
print(sentence.replace('Mike', 'Nancy'))   # 置換

11
20
2
My name is mike. hi mike
My Name Is Mike. Hi Mike
MY NAME IS MIKE. HI MIKE
my name is mike. hi mike
My name is Nancy. Hi Nancy


## format()メソッド

文字列の中に値を埋め込む．`{}` の位置に `format()` の引数が順番に入る．`{0}` のように番号や，`{first}` のように名前で指定することもできる．

In [140]:
sentence = 'a is {}'.format('a')
print(sentence)
sentence = 'The equation: {} + {} = {}'.format(1, 2, 3)
print(sentence)
a = 1
b = 2
c = a + b
sentence = 'The equation: {} + {} = {}'.format(a, b, c)
print(sentence)
sentence = 'The equation: {0} + {1} = {2}'.format(a, b, c)
print(sentence)
sentence = 'The equation: {2} + {1} = {0}'.format(a, b, c)
print(sentence)
print('#######################')
sentence = 'My name is {0} {1}.  Watashi ha {1} {0}'.format('Toshitaka', 'Matsuki')
print(sentence)
sentence = 'My name is {first} {last}.  Watashi ha {last} {first}'\
            .format(first='Toshitaka', last='Matsuki')
print(sentence)

a is a
The equation: 1 + 2 = 3
The equation: 1 + 2 = 3
The equation: 1 + 2 = 3
The equation: 3 + 2 = 1
#######################
My name is Toshitaka Matsuki.  Watashi ha Matsuki Toshitaka
My name is Toshitaka Matsuki.  Watashi ha Matsuki Toshitaka


## f文字列(f-strings)

`f'~~~{変数名}~~~'` のように，文字列の前に `f` をつけると `{}` の中に変数を直接埋め込める．

In [141]:
x = 1
y = 2
z = 3
sentence = f'The values {x}, {y}, {z}'
print(sentence)
print('#######################')
first = 'Toshitaka'
last = 'Matsuki'
print(f'My name is {first} {last}. Watashi ha {last} {first}')

The values 1, 2, 3
#######################
My name is Toshitaka Matsuki. Watashi ha Matsuki Toshitaka


## 課題7

> アプリケーション開発者になったつもりで，下記の文字列メソッドがそれぞれどんな時に使えるかを考え，それを説明してください．
> ・startswith ・find ・rfind ・count ・capitalize ・title ・upper ・lower ・replace

### 解答例

| メソッド | 機能 | アプリでの使いどころ（例） |
|---|---|---|
| `startswith()` | 指定した文字列で始まるか（bool） | URLが `https://` で始まるかチェックする，コマンド入力が `/` で始まればコマンドとして扱う |
| `find()` | 指定した文字列が最初に現れる位置（無ければ -1） | メールアドレスの `@` の位置を探してユーザー名部分を切り出す，検索語がヒットした位置をハイライトする |
| `rfind()` | 指定した文字列が最後に現れる位置 | ファイル名の最後の `.` の位置から拡張子を取り出す，パスの最後の `/` 以降のファイル名を取り出す |
| `count()` | 指定した文字列の出現回数 | 文章中のキーワードの出現回数を数える，入力に含まれる `@` が1個だけか確認する |
| `capitalize()` | 先頭の1文字だけ大文字・残りは小文字 | 入力された文の先頭を自動で大文字に直す（チャットの自動補正） |
| `title()` | 各単語の先頭を大文字 | 氏名や本・映画のタイトルの表記を整える（`john smith` → `John Smith`） |
| `upper()` | 全て大文字 | 郵便番号やクーポンコードを大文字に統一して照合する，見出しの強調表示 |
| `lower()` | 全て小文字 | メールアドレスやIDを小文字に統一して，大文字小文字の違いを無視して検索・ログイン判定する |
| `replace()` | 文字列の置換 | 全角スペースを半角に直す，テンプレート文の `{名前}` を実際の名前に差し替える，NGワードを伏せ字にする |

> ユーザーから何かの情報を入力してもらい，それを使ってなにかしらの処理をし，formatメソッドやf文字列を使ってその結果を表示するプログラムを書いてください．

### 解答例

In [142]:
# 名前とメールアドレスを入力してもらい, 表記を整えて会員カードを表示するプログラム
first_name = input('名前(ローマ字)を入力してください: ')
last_name = input('苗字(ローマ字)を入力してください: ')
email = input('メールアドレスを入力してください: ')

full_name = (first_name + ' ' + last_name).title()   # 先頭だけ大文字に整える
email = email.lower()                                  # メールアドレスは小文字に統一
user_name = email[:email.find('@')]                    # @ より前をユーザー名にする
domain = email[email.find('@') + 1:]                   # @ より後ろをドメインにする

print('=' * 30)
print('会員名      : {}'.format(full_name))
print('イニシャル  : {}.{}.'.format(first_name[0].upper(), last_name[0].upper()))
print(f'ユーザー名  : {user_name}')
print(f'ドメイン    : {domain}')
print(f'名前の文字数: {len(first_name) + len(last_name)} 文字')
print('=' * 30)

名前(ローマ字)を入力してください: toshitaka
苗字(ローマ字)を入力してください: matsuki
メールアドレスを入力してください: T_Matsuki@Example.com
会員名      : Toshitaka Matsuki
イニシャル  : T.M.
ユーザー名  : t_matsuki
ドメイン    : example.com
名前の文字数: 16 文字


## 辞書型について

キー(key)でオブジェクト(value)を管理する．`{key: value, ...}` の形で作り，`[key]` で紐付けた値を参照できる．

In [143]:
dictionary1 = {'orange': 100, 'apple': 200}
print(dictionary1)
print(dictionary1['orange'])
print(dictionary1['apple'])

{'orange': 100, 'apple': 200}
100
200


## 辞書型の要素の変更，追加

既にあるキーに代入すると値が変更され，無いキーに代入すると要素が追加される．キーになれるもの: bool値, 整数, float, タプル, 文字列など．

In [144]:
dictionary1['orange'] = 120
print(dictionary1)

{'orange': 120, 'apple': 200}


In [145]:
dictionary1['lemon'] = 300
print(dictionary1)

{'orange': 120, 'apple': 200, 'lemon': 300}


In [146]:
dictionary1[1] = 'xxxxx'    # 整数の1でもいい！
print(dictionary1)

{'orange': 120, 'apple': 200, 'lemon': 300, 1: 'xxxxx'}


## dict()を使った辞書の作り方

`dict()` を使って引数を辞書にして返すことができる．

In [147]:
dictionary2 = dict(x = 5, y = 6)
print(dictionary2)
dictionary2 = dict([['a', 1], ['b', 2]])
print(dictionary2)
dictionary2 = dict([('c', 50), ('d', 100)])
print(dictionary2)

{'x': 5, 'y': 6}
{'a': 1, 'b': 2}
{'c': 50, 'd': 100}


## 辞書型のメソッド1

- `keys()` : keyを取得する
- `values()` : valueを取得する
- `update()` : 辞書を結合する
- `get()` : keyの要素を参照する（無いkeyでもエラーにならず `None` が返る．`[key]` との違いを比べてみましょう）

In [148]:
dictionary1 = {'orange': 100, 'apple': 200}
print(dictionary1.keys())
print(dictionary1.values())

dict_keys(['orange', 'apple'])
dict_values([100, 200])


In [149]:
dictionary2 = {'orange': 400, 'lemon': 500}
dictionary1.update(dictionary2)
print(dictionary1)

{'orange': 400, 'apple': 200, 'lemon': 500}


In [150]:
print(dictionary1['orange'])
print(dictionary1.get('orange'))

400
400


In [151]:
print(dictionary1['grape'])

KeyError: 'grape'

In [152]:
print(dictionary1.get('grape'))

None


## 辞書型のメソッド2

`pop()` : 要素を取り出し削除

In [153]:
dictionary1 = {'x': 10, 'y': 20, 'z': 500}
print(dictionary1.pop('x'))
print(dictionary1)

10
{'y': 20, 'z': 500}


## 辞書型のコピー・辞書型を使うイメージ

辞書をコピーするときはリストと同じように `copy()` を使う．

In [154]:
x = {'a': 1}
y = x
print(x, y)
y['a'] = 2
print(x, y)

{'a': 1} {'a': 1}
{'a': 2} {'a': 2}


In [155]:
x = {'a': 1}
y = x.copy()
print(x, y)
y['a'] = 2
print(x, y)

{'a': 1} {'a': 1}
{'a': 1} {'a': 2}


In [156]:
#こんなイメージ
fruits_price = {
    'apple': 100,
    'banana': 200,
    'orange': 300
}
select = 'apple'
print('Price of', select, 'is', fruits_price[select])

Price of apple is 100


## 課題8

> 次のような手順で処理を実行するプログラムを書いてみてください
>
> **問1**
> - 辞書型変数に商品名と金額を代入しておく．("apple" ¥100, "lemon" ¥150, "grape" ¥200 とする)
> - いらっしゃいませと表示する．
> - なにを販売しているかの「リスト」を紹介する．
> - ユーザーから買いたいものの名前と個数を入力してもらう
> - 〇〇(商品名)を△△個で，お会計□□円です．のように表示する．
>
> ＊お客さんがここに無い商品を入力した時のことは考えない

### 解答例

In [157]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}

print('いらっしゃいませ')
print('商品リスト:', list(fruits_price.keys()))

item = input('何を買いますか?: ')
count = int(input('何個買いますか?: '))

total = fruits_price[item] * count
print(item, 'を', count, '個で, お会計', total, '円です.')

いらっしゃいませ
商品リスト: ['apple', 'lemon', 'grape']
何を買いますか?: lemon
何個買いますか?: 3
lemon を 3 個で, お会計 450 円です.


> **問2**
> - お店に追加する商品の名前と金額の入力を求め，商品を追加する．
> - その後一問目と同じ動作をする．

### 解答例

In [158]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}

# 商品の追加
new_name = input('追加する商品の名前: ')
new_price = int(input('その商品の金額: '))
fruits_price[new_name] = new_price
print(new_name, 'を', new_price, '円で追加しました.')

# 一問目と同じ動作
print('いらっしゃいませ')
print('商品リスト:', list(fruits_price.keys()))

item = input('何を買いますか?: ')
count = int(input('何個買いますか?: '))

total = fruits_price[item] * count
print(item, 'を', count, '個で, お会計', total, '円です.')

追加する商品の名前: melon
その商品の金額: 500
melon を 500 円で追加しました.
いらっしゃいませ
商品リスト: ['apple', 'lemon', 'grape', 'melon']
何を買いますか?: melon
何個買いますか?: 2
melon を 2 個で, お会計 1000 円です.


## 集合型(set型)

`{}` で要素を囲むと集合型になる．集合型は同じ要素を一つしか持たない．
積集合(`&`)，和集合(`|`)，差集合(`-`)，排他的論理和(`^`) を求めることができる．

In [159]:
#集合型 set型
set_a = {1, 2, 2, 3, 4, 4, 4, 5, 6}
print(set_a)
print(type(set_a))
set_b = {2, 3, 3, 6, 7}
print(set_b)


print('a and b:', set_a & set_b)
print('a or b:', set_a | set_b)
print('a - b:', set_a - set_b)
print('b - a:', set_b - set_a)
print('a exor b:', set_a ^ set_b)

{1, 2, 3, 4, 5, 6}
<class 'set'>
{2, 3, 6, 7}
a and b: {2, 3, 6}
a or b: {1, 2, 3, 4, 5, 6, 7}
a - b: {1, 4, 5}
b - a: {7}
a exor b: {1, 4, 5, 7}


`add()` で要素を追加．`remove()` で要素を削除．`clear()` で全ての要素を削除．
変数に `{}` を代入したら辞書型になってしまうので注意しましょう．

In [160]:
test_set = {1, 2, 3, 4, 5}
print(test_set)
test_set.add(6)
print(test_set)
test_set.remove(2)
print(test_set)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 3, 4, 5, 6}


In [161]:
test_set.clear()
print(test_set)
print(type(test_set))

set()
<class 'set'>


In [162]:
test_object = {}
print(test_object)
print(type(test_object))

{}
<class 'dict'>


## Pythonのif文

```
if 条件式:
    処理        ← 条件が成り立つ(True)なら実行
else:
    処理        ← 条件が成り立たない(False)なら実行
```

- `if` の後にスペースを入れて条件式を書き，最後に `:` で終わる（`( )` はいらない）．
- 字下げ（インデント）でif文の範囲を示す．揃えて字下げしている範囲をif文の中身と認識する．
- `int()` でint型に変換する．`f'~{変数名}~~~'` で文字列に変数を埋め込める．

In [163]:
age = int(input('あなたは何歳ですか? :'))
if age >= 20:
    print(f'{age}歳であればお酒が飲めます.')
else:
    print('あなたはjuiceしか飲めません.')

あなたは何歳ですか? :25
25歳であればお酒が飲めます.


## elif で複数条件を並べる

条件式1から $n$ までを順番に検証し，Trueならそのブロック内の処理を実行しif文を抜ける．Trueになる条件式がなければ `else` 内の処理を実行．

In [164]:
order = input("'beer'と'wine'と'juice'のどちらがよろしいですか?:")
if order == 'beer':
    print("'beer'をどうぞ.")
elif order == 'wine':
    print("'wine'をどうぞ.")
elif order == 'juice':
    print("'juice'をどうぞ.")
else:
    print(order, 'は,メニューにございません.')

'beer'と'wine'と'juice'のどちらがよろしいですか?:wine
'wine'をどうぞ.


## if文の中にif文があって構わない

ただし3層くらいまでにすること（読みにくいから）．

In [165]:
age = int(input('あなたは何歳ですか? :'))
if age >= 20:
    print(f'{age}歳であればお酒が飲めます.')
    order = input("'beer'と'wine'と'juice'のどちらがよろしいですか?:")
    if order == 'beer':
        print("'beer'をどうぞ.")
    elif order == 'wine':
        print("'wine'をどうぞ.")
    elif order == 'juice':
        print("'juice'をどうぞ.")
    else:
        print(order, 'は,メニューにございません.')
else:
    print('あなたはjuiceしか飲めません.')

あなたは何歳ですか? :30
30歳であればお酒が飲めます.
'beer'と'wine'と'juice'のどちらがよろしいですか?:beer
'beer'をどうぞ.


## 比較演算子や論理演算子を使ったif文

| 比較演算子 | 意味 |
|---|---|
| `<`, `<=`, `>`, `>=` | ＜, ≦, ＞, ≧ |
| `!=` | ≠ |
| `==` | ＝ |

| 論理演算子 | 意味 |
|---|---|
| `x and y` | x かつ y（両方Trueのとき True） |
| `x or y` | x または y（どちらかがTrueなら True） |
| `not x` | x の否定 |

In [166]:
a = int(input('aの値は? :'))
b = int(input('bの値は? :'))

if a > 0 and b > 0:
    print('aもbも正の数です.')
elif a > 0 or b > 0:
    print('aとbのどちらか一方だけが正の数です.')
else:
    print('aもbも正の数ではありません.')

if not a == b:          # a != b と同じ
    print('aとbは異なる値です.')
else:
    print('aとbは同じ値です.')

if a <= b <= 10:        # 比較は連結できる (a <= b and b <= 10 と同じ)
    print('bはa以上10以下です.')

aの値は? :3
bの値は? :-5
aとbのどちらか一方だけが正の数です.
aとbは異なる値です.


## 課題9

> 次のような手順で処理を実行するプログラムを書いてみてください
> - いらっしゃいませと表示する．
> - 販売しているものの「リスト」を紹介する．
> - ユーザーから買いたいものと個数を入力してもらう
> - 店頭にないものの場合は謝って終了する
> - 〇を△個ですね，合計□□円です．のように表示する．
> - お店の在庫は「apple(¥100)」，「lemon(¥150)」，「grape(¥200)」
> - お客が500円を払ったとして，お釣を計算し，〇〇円のお返しですと表示する．足りない場合は足りません，と表示する．

### 解答例

In [167]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}
payment = 500

print('いらっしゃいませ')
print('商品リスト:', list(fruits_price.keys()))

item = input('何を買いますか?: ')
if item in fruits_price:
    count = int(input('何個買いますか?: '))
    total = fruits_price[item] * count
    print(item, 'を', count, '個ですね, 合計', total, '円です.')

    if payment >= total:
        print(payment - total, '円のお返しです.')
    else:
        print('足りません.')
else:
    print('申し訳ありません,', item, 'は店頭にございません.')

いらっしゃいませ
商品リスト: ['apple', 'lemon', 'grape']
何を買いますか?: grape
何個買いますか?: 2
grape を 2 個ですね, 合計 400 円です.
100 円のお返しです.


> 次のような手順で処理を実行するプログラムを書いてみてください
> - ユーザーが管理者かどうかを問いかける．
> - 管理者ならパスワードを聞き正解なら管理モードへ不正解なら動作を終了する
> - 管理モードでは，追加する商品名と金額を入れてもらう．
> - 商品の追加が終わった後や，ユーザーが管理者でなかった場合は一問目と同じように動作する．

### 解答例

「動作を終了する」を実現するために，買い物に進んでよいかどうかを変数 `shopping` (bool型) に入れておき，最後にそれで分岐している．

In [168]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}
password = 'denki'
payment = 500

is_admin = input('あなたは管理者ですか? (y/n): ')
if is_admin == 'y':
    user_password = input('パスワードを入力してください: ')
    if user_password == password:
        print('管理モードに入ります.')
        new_name = input('追加する商品の名前: ')
        new_price = int(input('その商品の金額: '))
        fruits_price[new_name] = new_price
        print(new_name, 'を', new_price, '円で追加しました.')
        shopping = True
    else:
        print('パスワードが違います. 終了します.')
        shopping = False
else:
    shopping = True

if shopping:
    print('いらっしゃいませ')
    print('商品リスト:', list(fruits_price.keys()))

    item = input('何を買いますか?: ')
    if item in fruits_price:
        count = int(input('何個買いますか?: '))
        total = fruits_price[item] * count
        print(item, 'を', count, '個ですね, 合計', total, '円です.')

        if payment >= total:
            print(payment - total, '円のお返しです.')
        else:
            print('足りません.')
    else:
        print('申し訳ありません,', item, 'は店頭にございません.')

あなたは管理者ですか? (y/n): y
パスワードを入力してください: denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 300
melon を 300 円で追加しました.
いらっしゃいませ
商品リスト: ['apple', 'lemon', 'grape', 'melon']
何を買いますか?: melon
何個買いますか?: 2
melon を 2 個ですね, 合計 600 円です.
足りません.


## Pythonのfor文

```
for 変数 in イテラブルオブジェクト:
    処理
```

イテラブルオブジェクト（中の値を順番に取り出すことのできるオブジェクト．要はリスト・文字列・タプル・辞書・集合・その他のこと）の中身を順番に変数に代入しながら処理を繰り返す．

In [169]:
for iii in [1, 2, 7]:
    print(iii)

1
2
7


In [170]:
for iii in ['大分', '熊本', '福岡']:
    print(iii)

大分
熊本
福岡


## range()での数列生成

`range()` でrangeオブジェクトが生成される．`list()` でリストに変換するとこうなる．範囲やステップの指定も可能．

In [171]:
range(5)

range(0, 5)

In [172]:
list(range(5))

[0, 1, 2, 3, 4]

In [173]:
list(range(3, 7))

[3, 4, 5, 6]

In [174]:
list(range(3, 10, 2))

[3, 5, 7, 9]

## range()での数列生成とfor文

`for iii in range(3):` は「3回繰り返す」というのが明確．rangeを使ってfor文の繰り返しをすることは多い．

In [175]:
for iii in range(3):
    print(iii)

0
1
2


In [176]:
for iii in range(2, 5):
    print(iii)

2
3
4


In [177]:
for iii in range(1, 6, 2):
    print(iii)

1
3
5


## breakでforループを抜け出す

`break` を使うとforループから強制的に抜け出すことができる．

In [178]:
for iii in range(3):
    print(iii)

0
1
2


In [179]:
for iii in range(3):
    print(iii)
    if iii == 1:
        break

0
1


## for文のelse

for文にelseの節を書くと最後に一度だけ実行される．breakで抜けた場合else節は実行されない．

In [180]:
for iii in range(3):
    print(iii)
else:
    print('complete!')

0
1
2
complete!


In [181]:
for iii in range(3):
    print(iii)
    if iii == 1:
        break
else:
    print('complete!')

0
1


## for文の中にfor文

forループをさらにforループで繰り返すことができる．

In [182]:
for iii in range(3):
    for jjj in range(3):
        print(iii, jjj)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


## if文の中にfor文

In [183]:
a = int(input('偶数aの値は? :'))

if a % 2 == 0:
    for iii in range(a):
        print(iii)
else:
    print('aは偶数にしてください.')

偶数aの値は? :4
0
1
2
3


## for文の中にif文

In [184]:
a = int(input('aの値は? :'))
for iii in range(a):
    if iii % 2 == 0:
        print(iii)
    else:
        print('[奇数]')

aの値は? :5
0
[奇数]
2
[奇数]
4


## 課題10

> 課題9の二問目で作成したプログラムに次のような変更を加えてみてください．
> - 管理者のパスワードを3回まで入力できるようにする．
> - 商品名の紹介と同時にそれがいくらなのかも一つづつ表示する．
> - 3種類まで購入できるようにする．（購入点数も，それぞれ選べるように）
> - 支払う金額をユーザーが入力できるようにする（500円で固定ではなく）

### 解答例

- パスワードは `for ... in range(3)` で3回まで繰り返し，正解なら `break`．3回とも間違えたときは for文の `else` で終了処理をする．
- 商品の紹介は辞書を for文で回す（辞書を for で回すとキーが順番に取り出せる）．
- 購入は3回繰り返す for文の中で商品を聞き，途中でやめたいときは `q` を入力すると `break` する．

In [185]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}
password = 'denki'

shopping = True
is_admin = input('あなたは管理者ですか? (y/n): ')
if is_admin == 'y':
    for i in range(3):                       # パスワードは3回まで
        user_password = input('パスワードを入力してください: ')
        if user_password == password:
            print('管理モードに入ります.')
            new_name = input('追加する商品の名前: ')
            new_price = int(input('その商品の金額: '))
            fruits_price[new_name] = new_price
            print(new_name, 'を', new_price, '円で追加しました.')
            break
        else:
            print('パスワードが違います. (残り', 2 - i, '回)')
    else:                                    # 3回とも間違えたとき
        print('3回間違えたので終了します.')
        shopping = False

if shopping:
    print('いらっしゃいませ')
    print('商品リスト:')
    for name in fruits_price:                # 商品名と値段を一つずつ表示
        print('  ', name, ':', fruits_price[name], '円')

    total = 0
    for i in range(3):                       # 3種類まで購入できる
        item = input('何を買いますか? (やめる場合は q): ')
        if item == 'q':
            break
        if item in fruits_price:
            count = int(input('何個買いますか?: '))
            print(item, 'を', count, '個ですね.')
            total += fruits_price[item] * count
        else:
            print('申し訳ありません,', item, 'は店頭にございません.')

    print('合計', total, '円です.')
    if total > 0:
        payment = int(input('お支払い金額を入力してください: '))
        if payment >= total:
            print(payment - total, '円のお返しです.')
        else:
            print('足りません.')

あなたは管理者ですか? (y/n): y
パスワードを入力してください: kikai
パスワードが違います. (残り 2 回)
パスワードを入力してください: denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 300
melon を 300 円で追加しました.
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
   melon : 300 円
何を買いますか? (やめる場合は q): apple
何個買いますか?: 2
apple を 2 個ですね.
何を買いますか? (やめる場合は q): banana
申し訳ありません, banana は店頭にございません.
何を買いますか? (やめる場合は q): melon
何個買いますか?: 1
melon を 1 個ですね.
合計 500 円です.
お支払い金額を入力してください: 1000
500 円のお返しです.


## while文

```
while 条件式:
    処理
```

条件式が **真** である限りずっと処理を繰り返す．

In [186]:
a = 0
while a < 3:
    print(a)
    a += 1

0
1
2


## while文のelse

else節でループを抜け出した時だけやる処理を決めることができる．

In [187]:
command = ''
while command != 'denki':
    command = input('合言葉は? :')
else:
    print('正解!')

合言葉は? :kikai
合言葉は? :chinou
合言葉は? :denki
正解!


## while文におけるbreak

breakを使えば条件式が成り立っていなくてもループを抜け出せる．breakした場合else節は実行されない．

In [188]:
command = ''
count = 0
while command != 'denki':
    command = input('合言葉は? :')
    count += 1
    if count == 5:
        print('5回間違えたので失敗です.')
        break
else:
    print('正解!')

合言葉は? :kikai
合言葉は? :chinou
合言葉は? :zairyo
合言葉は? :kenchiku
合言葉は? :ouyou
5回間違えたので失敗です.


## while文におけるcontinue

`continue` で強制的に振り出しに戻る（それ以降の処理を飛ばして次の繰り返しへ）．`while True:` は無限ループなので，`break` で抜ける．

In [189]:
command = ''
while True:
    command = input('合言葉は? :')
    if command != 'denki':
        continue
    print('正解!')
    break

合言葉は? :kikai
合言葉は? :denki
正解!


## 課題11

> 課題10の二問目で作成したプログラムに次のような変更を加えてみてください．
> - 管理者のパスワード何度でも入力できるようにする．
> - その代わりユーザーの意思でパスワード入力から抜けられる方法を用意する．
> - 購入できる種類の制限をなくす．（3種類以上も買えるようにする）
> - 購入まで完了したらまた初めからスタートする．

### 解答例

- 全体を `while True:` で囲んで，購入が終わったら最初に戻る．（ノートブック上で止められるように，最初の問いかけで `q` を入力するとプログラムを終了するようにした）
- パスワード入力も `while True:` で何度でも聞き，正解なら管理モードへ，`q` が入力されたらパスワード入力をやめて `break` する．
- 購入も `while True:` で何種類でも聞き，`q` で終了する．

In [190]:
fruits_price = {'apple': 100, 'lemon': 150, 'grape': 200}
password = 'denki'

while True:                                     # 購入が終わったら最初に戻る
    print('=' * 30)
    is_admin = input('あなたは管理者ですか? (y/n, 終了する場合は q): ')
    if is_admin == 'q':
        print('終了します.')
        break

    if is_admin == 'y':
        while True:                             # パスワードは何度でも入力できる
            user_password = input('パスワードを入力してください (やめる場合は q): ')
            if user_password == password:
                print('管理モードに入ります.')
                new_name = input('追加する商品の名前: ')
                new_price = int(input('その商品の金額: '))
                fruits_price[new_name] = new_price
                print(new_name, 'を', new_price, '円で追加しました.')
                break
            elif user_password == 'q':
                print('パスワード入力をやめました.')
                break
            else:
                print('パスワードが違います.')

    print('いらっしゃいませ')
    print('商品リスト:')
    for name in fruits_price:
        print('  ', name, ':', fruits_price[name], '円')

    total = 0
    while True:                                 # 何種類でも購入できる
        item = input('何を買いますか? (やめる場合は q): ')
        if item == 'q':
            break
        if item in fruits_price:
            count = int(input('何個買いますか?: '))
            print(item, 'を', count, '個ですね.')
            total += fruits_price[item] * count
        else:
            print('申し訳ありません,', item, 'は店頭にございません.')

    print('合計', total, '円です.')
    if total > 0:
        payment = int(input('お支払い金額を入力してください: '))
        if payment >= total:
            print(payment - total, '円のお返しです.')
        else:
            print('足りません.')
    print('ありがとうございました.')

あなたは管理者ですか? (y/n, 終了する場合は q): y
パスワードを入力してください (やめる場合は q): kikai
パスワードが違います.
パスワードを入力してください (やめる場合は q): q
パスワード入力をやめました.
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
何を買いますか? (やめる場合は q): apple
何個買いますか?: 1
apple を 1 個ですね.
何を買いますか? (やめる場合は q): q
合計 100 円です.
お支払い金額を入力してください: 100
0 円のお返しです.
ありがとうございました.
あなたは管理者ですか? (y/n, 終了する場合は q): y
パスワードを入力してください (やめる場合は q): denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 300
melon を 300 円で追加しました.
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
   melon : 300 円
何を買いますか? (やめる場合は q): apple
何個買いますか?: 2
apple を 2 個ですね.
何を買いますか? (やめる場合は q): lemon
何個買いますか?: 1
lemon を 1 個ですね.
何を買いますか? (やめる場合は q): grape
何個買いますか?: 1
grape を 1 個ですね.
何を買いますか? (やめる場合は q): melon
何個買いますか?: 1
melon を 1 個ですね.
何を買いますか? (やめる場合は q): q
合計 850 円です.
お支払い金額を入力してください: 1000
150 円のお返しです.
ありがとうございました.
あなたは管理者ですか? (y/n, 終了する場合は q): q
終了します.


## 関数のパターン

| 引数 | 戻り値 | 説明 |
|---|---|---|
| なし | なし | 引数を受け取らないし戻り値も返さない |
| あり | なし | 引数は受け取るが戻り値は返さない |
| なし | あり | 引数は受け取らないが戻り値を返す |
| あり | あり | 引数を受け取り戻り値を返す |

## 関数の作り方

```
def 関数名():
    処理
```

これで関数ができた．呼び出して使える．

In [191]:
def greeting():
    print('こんにちは!')

In [192]:
greeting()

こんにちは!


## 引数を受け取る関数

```
def 関数名(引数名):
    処理
```

In [193]:
def greeting2(name):
    print(name+'さん, こんにちは!')

In [194]:
greeting2('柴田')

柴田さん, こんにちは!


## 引数を受け取り，戻り値を返す関数

複数の引数も受け取れる．`return` で変数を返して終了．

In [195]:
def tashizan(value1, value2):
    result = value1 + value2
    return result

In [196]:
kekka = tashizan(1,3)
print(kekka)

4


## 処理をreturnしても良い！

`return` の所に処理を書く．結果は同じ！コードが短くなってよりスマートに！戻り値をそのまま `print` してるのにも注目！

In [197]:
def tashizan2(value1, value2):
    return value1 + value2

In [198]:
print(tashizan2(1, 3))

4


## キーワード引数！

しっかり引数名を指定することもできる．順番を入れ替えても大丈夫．ただしキーワード引数は必ず後ろに！（`tashizan2(value1=1, 3)` はダメ）

In [199]:
print(tashizan2(value1=1, value2=3))

4


In [200]:
print(tashizan2(value2=1, value1=3))

4


In [201]:
print(tashizan2(1, value2=3))

4


In [202]:
print(tashizan2(value1=1, 3))

SyntaxError: positional argument follows keyword argument (3753429563.py, line 1)

## どんなオブジェクトでもreturnできる！

`return` の所は文字列だって大丈夫！

In [203]:
def tashizan3(value1, value2):
    return '答えは' + str(value1 + value2) + 'です'

In [204]:
print(tashizan3(1, 4))

答えは5です


## 引数にデフォルト値を決めておける！

引数にあらかじめ値を入れておけばデフォルト値を設定できる．引数がなくても実行可能．もちろん引数を入れても実行可能．

In [205]:
def tashizan4(value1=1, value2=2):
    return value1 + value2

In [206]:
tashizan4()

3

In [207]:
tashizan4(2, 4)

6

## 名前空間1

関数の外で定義した変数（グローバル変数）は，関数内（ローカル空間）から取得できる．

In [208]:
name = 'shibata'

print(name)

shibata


In [209]:
name = 'shibata'

def print_global():
    print(name)

print_global()

shibata


## 名前空間2

これはダメ！グローバル変数にローカル空間で値を代入することはできない（`UnboundLocalError`）．

In [210]:
name = 'shibata'

def change_global():
    print(name)
    name = 'matsuki'

change_global()

UnboundLocalError: cannot access local variable 'name' where it is not associated with a value

## 名前空間3

これは大丈夫！ただし…参照する前に定義するとローカル変数になる（グローバル変数とは別物！）．

In [211]:
name = 'shibata'

def define_local():
    name = 'matsuki'
    print(name)

define_local()
print(name)

matsuki
shibata


## 名前空間4

`global` を使うと関数内でもグローバル変数と同じものを扱える．ただしあまりglobalを使わない方が良い気がする…

In [212]:
name = 'shibata'

def access_global():
    global name
    print(name)
    name = 'matsuki'
    print(name)

access_global()
print(name)

shibata
matsuki
matsuki


## 課題12

> 課題11までのプログラムを関数を使って書き改めてみてください．次のような関数を盛り込んで見る．
> - 管理者モード関数と購入者モード関数
> - パスワード処理をする関数
> - 商品を追加する関数
> - お客さんが購入する関数
> - 商品を紹介する関数
> - 買うものを選択する関数
> - 会計を計算する関数
> - 支払い額に対して反応する関数
>
> メインのループはこんな風にスッキリとさせる．
> ```python
> fruits_price = {"apple":100, "lemon":150, "grape":200}
> while(True):
>     permission = input("あなたは管理者ですか?y/n>>>")
>     if permission == "y":
>         fruits_price = admin_mode(fruits_price)
>     else:
>         user_mode(fruits_price)
> ```

### 解答例

まず関数を定義する（この時点では何も実行されない）．

In [213]:
PASSWORD = 'denki'


def check_password():
    """パスワード処理をする関数. 正解なら True, ユーザーがやめたら False を返す."""
    while True:
        user_password = input('パスワードを入力してください (やめる場合は q): ')
        if user_password == PASSWORD:
            return True
        elif user_password == 'q':
            print('パスワード入力をやめました.')
            return False
        else:
            print('パスワードが違います.')


def add_product(fruits_price):
    """商品を追加する関数. 追加後の辞書を返す."""
    new_name = input('追加する商品の名前: ')
    new_price = int(input('その商品の金額: '))
    fruits_price[new_name] = new_price
    print(new_name, 'を', new_price, '円で追加しました.')
    return fruits_price


def admin_mode(fruits_price):
    """管理者モード関数. パスワードが正しければ商品を追加し, 辞書を返す."""
    if check_password():
        print('管理モードに入ります.')
        fruits_price = add_product(fruits_price)
    return fruits_price


def show_products(fruits_price):
    """商品を紹介する関数."""
    print('いらっしゃいませ')
    print('商品リスト:')
    for name in fruits_price:
        print('  ', name, ':', fruits_price[name], '円')


def select_items(fruits_price):
    """買うものを選択する関数. {商品名: 個数} の辞書(カート)を返す."""
    cart = {}
    while True:
        item = input('何を買いますか? (やめる場合は q): ')
        if item == 'q':
            break
        if item in fruits_price:
            count = int(input('何個買いますか?: '))
            print(item, 'を', count, '個ですね.')
            cart[item] = count
        else:
            print('申し訳ありません,', item, 'は店頭にございません.')
    return cart


def calc_total(fruits_price, cart):
    """会計を計算する関数. 合計金額を返す."""
    total = 0
    for item in cart:
        total += fruits_price[item] * cart[item]
    return total


def respond_payment(total, payment):
    """支払い額に対して反応する関数."""
    if payment >= total:
        print(payment - total, '円のお返しです.')
    else:
        print('足りません.')


def purchase(fruits_price):
    """お客さんが購入する関数."""
    cart = select_items(fruits_price)
    total = calc_total(fruits_price, cart)
    print('合計', total, '円です.')
    if total > 0:
        payment = int(input('お支払い金額を入力してください: '))
        respond_payment(total, payment)
    print('ありがとうございました.')


def user_mode(fruits_price):
    """購入者モード関数."""
    show_products(fruits_price)
    purchase(fruits_price)

メインのループ．（ノートブック上で止められるように `q` で終了できるようにしてある）

In [214]:
fruits_price = {"apple": 100, "lemon": 150, "grape": 200}
while(True):
    permission = input("あなたは管理者ですか?y/n (終了はq)>>>")
    if permission == "q":
        print('終了します.')
        break
    elif permission == "y":
        fruits_price = admin_mode(fruits_price)
    else:
        user_mode(fruits_price)

あなたは管理者ですか?y/n (終了はq)>>>y
パスワードを入力してください (やめる場合は q): denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 300
melon を 300 円で追加しました.
あなたは管理者ですか?y/n (終了はq)>>>n
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
   melon : 300 円
何を買いますか? (やめる場合は q): melon
何個買いますか?: 2
melon を 2 個ですね.
何を買いますか? (やめる場合は q): apple
何個買いますか?: 3
apple を 3 個ですね.
何を買いますか? (やめる場合は q): q
合計 900 円です.
お支払い金額を入力してください: 1000
100 円のお返しです.
ありがとうございました.
あなたは管理者ですか?y/n (終了はq)>>>q
終了します.


## 復習！！

if文，for文，while文，関数の自作．

## 今回！！ クラスの自作

**クラスとはデータ型のことである**（データ型 ＝ クラス）．クラスは 変数（属性，アトリビュート）と 関数（メソッド）によって構成されている．
クラスとはオブジェクトの設計図あるいは金型のようなもの．クラスから実体を作ることを **インスタンス化** という．

## インスタンス化の実例

`a = 1`, `b = int(3)`, `c = str(10)`, `birth_day = datetime.date(1988, 5, 6)` はそれぞれ int, int, string, date クラスのインスタンス．

In [215]:
import datetime
a = 1
b = int(3)
c = str(10)
birth_day = datetime.date(1988, 5, 6)
print(type(a), type(b), type(c), type(birth_day))

<class 'int'> <class 'int'> <class 'str'> <class 'datetime.date'>


## 実際にクラスを作ってみよう

```
class クラス名():
    定義      ← ここに変数・メソッドを書く
```

初期化メソッド `__init__(self)` はインスタンス化の際に一度だけ実行される．

In [216]:
class Human():
    def __init__(self):
        self.name = '松木'

## 作ったクラスをインスタンス化してみよう

In [217]:
person = Human()

In [218]:
print(person.name)

松木


In [219]:
person.name = '柴田'
print(person.name)

柴田


## 初期化メソッドに引数を持たせる

In [220]:
class Human():
    def __init__(self, name):
        self.name = name

In [221]:
person = Human('松木')

In [222]:
print(person.name)

松木


## メソッドを作ろう

```
class クラス名(引数):
    ...
    def メソッド名(引数):
        処理
```

`name` という変数と `greeting` という関数を持ったクラスの出来上がり！！一つのクラスを元にいくらでもインスタンス化できる！

In [223]:
class Human:
    def __init__(self, name):
        self.name = name

    def greeting(self):
        print("こんにちは, 私は"+self.name+'です.')

In [224]:
person1 = Human('松木')
person2 = Human('柴田')
person1.greeting()
person2.greeting()

こんにちは, 私は松木です.
こんにちは, 私は柴田です.


## selfの意味

`self` には自分がどのインスタンスなのか，という情報が入っている．`self` を付けた変数はインスタンスの中に残り続ける．

## selfが無かったら？

`self` の無い変数は，関数が実行し終えると消えてしまう．`greeting()` 関数は，消えてしまった `my_name` のことを知らないのでエラーになる．

In [225]:
class Human:
    def __init__(self, name):
        my_name = name

    def greeting(self):
        print("こんにちは, 私は"+my_name+'です.')

person = Human('松木')
person.greeting()

NameError: name 'my_name' is not defined

## classの継承

新しくクラスを作るとき，親クラスから能力を継承できる！！継承した場合，親クラスを修正すると子クラスも変わる．
（Carクラスにあらゆる車種の機能を書き込まなくて済む．共通機能はCarクラスだけ修正すれば全クラスに波及する．）

## クラスの継承をやってみよう

引数に親クラスを入れ，独自の機能を書いていく．親クラスHumanから継承して子クラスStudentを作り，独自関数study()を追加した．

In [226]:
class Human:
    def __init__(self, name):
        self.name = name

    def greeting(self):
        print("こんにちは, 私は"+self.name+'です.')

In [227]:
class Student(Human):
    def study(self):
        print("私は勉強します.")

## Studentクラスを使ってみる

独自の機能も，親クラスの機能も使うことができる．

In [228]:
person = Student('松木')

In [229]:
person.study()

私は勉強します.


In [230]:
person.greeting()

こんにちは, 私は松木です.


## オーバーライト

親クラスが持っている `greeting()` 関数を上書きした．親クラスには何の影響もない．

In [231]:
class Student(Human):
    def study(self):
        print("私は勉強します.")

    def greeting(self):
        print('私は,大分大学の'+self.name+'です.')

In [232]:
person = Student('松木')
person.greeting()

私は,大分大学の松木です.


In [233]:
person = Human('松木')    # 親クラスには影響がない
person.greeting()

こんにちは, 私は松木です.


## フリーザ様クラスを作る

初期化メソッドをオーバーライトし，`power` 変数を追加．`self_introduction()` 関数を定義した．

In [234]:
class Freezer(Human):
    def __init__(self, name='フリーザ様', power=530000):
        self.name = name
        self.power = power

    def self_introduction(self):
        print('私の戦闘力は'+str(self.power)+'です.')

In [235]:
enemy = Freezer()
enemy.self_introduction()

私の戦闘力は530000です.


In [236]:
enemy.greeting()

こんにちは, 私はフリーザ様です.


## 親のメソッドを使いつつオーバーライト

`super()` を使うとオーバーライトした場合でも親クラスのメソッドを呼び出せる．こうすると上書きではなく **加筆** することができる．

In [237]:
class Freezer(Human):
    def __init__(self, name='フリーザ様', power=530000):
        super().__init__(name)
        self.power = power

    def self_introduction(self):
        print('私の戦闘力は'+str(self.power)+'です.')

In [238]:
enemy = Freezer()
enemy.self_introduction()
enemy.greeting()

私の戦闘力は530000です.
こんにちは, 私はフリーザ様です.


## 課題13

> 課題12までと同じように動作する．Store クラスを作ってみる．
> - 必要に応じて変数はインスタンス変数として管理（self.〜〜）
> - 次のような処理をする関数をメソッドとしてもつ
>   - 管理者モードか購入モードかを選択してもらう
>   - パスワードを確認した後，商品を追加する
>   - 売っている商品を紹介する
>   - お客さんに商品を選んでもらう
>   - 会計を計算する
>   - 支払い金額を聞く
>   - お礼や，お返しを伝える
>
> メインループの例
> ```python
> store = Store()
> store.set_products({"apple":100, "lemon":150, "grape":200})
>
> while(True):
>     mode = store.mode_select()
>     if mode == "admin":
>         store.admin_mode()
>     elif mode == "customer":
>         store.customer_mode()
> ```

### 解答例

商品の辞書 `self.products`，パスワード `self.password`，お客さんが選んだ商品 `self.cart` をインスタンス変数として持たせる．

In [239]:
class Store:
    def __init__(self, password='denki'):
        self.products = {}          # {商品名: 金額}
        self.password = password
        self.cart = {}              # {商品名: 個数}

    def set_products(self, products):
        """商品の辞書をセットする."""
        self.products = products

    def mode_select(self):
        """管理者モードか購入モードかを選択してもらう."""
        print('=' * 30)
        answer = input('あなたは管理者ですか? (y/n, 終了する場合は q): ')
        if answer == 'q':
            return 'quit'
        elif answer == 'y':
            return 'admin'
        else:
            return 'customer'

    def check_password(self):
        """パスワードを確認する. 正解なら True, やめたら False."""
        while True:
            user_password = input('パスワードを入力してください (やめる場合は q): ')
            if user_password == self.password:
                return True
            elif user_password == 'q':
                print('パスワード入力をやめました.')
                return False
            else:
                print('パスワードが違います.')

    def add_product(self):
        """商品を追加する."""
        new_name = input('追加する商品の名前: ')
        new_price = int(input('その商品の金額: '))
        self.products[new_name] = new_price
        print(new_name, 'を', new_price, '円で追加しました.')

    def admin_mode(self):
        """パスワードを確認した後, 商品を追加する."""
        if self.check_password():
            print('管理モードに入ります.')
            self.add_product()

    def show_products(self):
        """売っている商品を紹介する."""
        print('いらっしゃいませ')
        print('商品リスト:')
        for name in self.products:
            print('  ', name, ':', self.products[name], '円')

    def select_items(self):
        """お客さんに商品を選んでもらう."""
        self.cart = {}
        while True:
            item = input('何を買いますか? (やめる場合は q): ')
            if item == 'q':
                break
            if item in self.products:
                count = int(input('何個買いますか?: '))
                print(item, 'を', count, '個ですね.')
                self.cart[item] = count
            else:
                print('申し訳ありません,', item, 'は店頭にございません.')

    def calc_total(self):
        """会計を計算する."""
        total = 0
        for item in self.cart:
            total += self.products[item] * self.cart[item]
        return total

    def ask_payment(self, total):
        """支払い金額を聞く."""
        print('合計', total, '円です.')
        payment = int(input('お支払い金額を入力してください: '))
        return payment

    def respond_payment(self, total, payment):
        """お礼や, お返しを伝える."""
        if payment >= total:
            print(payment - total, '円のお返しです. ありがとうございました.')
        else:
            print('足りません.')

    def customer_mode(self):
        """購入モード."""
        self.show_products()
        self.select_items()
        total = self.calc_total()
        if total > 0:
            payment = self.ask_payment(total)
            self.respond_payment(total, payment)
        else:
            print('またのお越しをお待ちしております.')

メインループ．（`mode_select()` で `q` を入力すると `"quit"` が返るようにして，ループを抜けられるようにした）

In [240]:
store = Store()
store.set_products({"apple": 100, "lemon": 150, "grape": 200})

while(True):
    mode = store.mode_select()
    if mode == "admin":
        store.admin_mode()
    elif mode == "customer":
        store.customer_mode()
    elif mode == "quit":
        print('終了します.')
        break

あなたは管理者ですか? (y/n, 終了する場合は q): y
パスワードを入力してください (やめる場合は q): denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 300
melon を 300 円で追加しました.
あなたは管理者ですか? (y/n, 終了する場合は q): n
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
   melon : 300 円
何を買いますか? (やめる場合は q): melon
何個買いますか?: 1
melon を 1 個ですね.
何を買いますか? (やめる場合は q): grape
何個買いますか?: 2
grape を 2 個ですね.
何を買いますか? (やめる場合は q): q
合計 700 円です.
お支払い金額を入力してください: 500
足りません.
あなたは管理者ですか? (y/n, 終了する場合は q): q
終了します.


## ドラクエっぽいクラスを作ってみよう

`Character` クラス : `name`, `hp`, `max_hp`, `strength`, `luck` の変数と `damage()`, `status()`, `attack()` のメソッドを持つ．

- `__init__` : パラメータの初期化（名前，HP，最大HP，こうげき力，運）
- `damage(value)` : ダメージを受ける関数．`value` はダメージの値（負にならないようにする）．hpからダメージを引き，hpが負にならないようにする．luckの確率で避ける．
- `status()` : ステータスを表示する関数
- `attack(target_object)` : 攻撃する関数．引数は攻撃相手のオブジェクトで，相手の `damage` 関数を実行する．luckの確率で倍のダメージ．

In [241]:
import random
class Character:
    def __init__(self, name, hp=100, strength=20, luck=20):
        self.name = name
        self.hp = hp
        self.max_hp = hp
        self.strength = strength
        self.luck = luck

    def damage(self, value):
        damage_value = max(1, value)
        if random.randint(0, 100) > self.luck:
            self.hp -= damage_value
            self.hp = max(self.hp, 0)
            print(self.name, 'は', damage_value, 'のダメージ!')
        else:
            print(self.name, 'は ひらりとみをかわした.')

    def status(self):
        print('#名前:', self.name, '\t#HP:', self.hp)

    def attack(self, target_object):
        if random.randint(0, 100) > self.luck:
            print(self.name+'のこうげき!')
            target_object.damage(self.strength)
        else:
            print(self.name+'のかいしんのいちげき!!!')
            target_object.damage(self.strength*2.0)

スライムA, Bをインスタンス化して遊んでみる．（乱数を使っているので，実行するたびに結果が変わる）

In [242]:
monsterA = Character('スライムA')
monsterB = Character('スライムB')

In [243]:
monsterB.status()
monsterA.attack(monsterB)
monsterB.status()

#名前: スライムB 	#HP: 100
スライムAのこうげき!
スライムB は ひらりとみをかわした.
#名前: スライムB 	#HP: 100


## 勇者クラス

Characterクラスを継承してHeroクラスを作成．`mp` と `magic` を追加し，独自機能として回復魔法 `magic_heal()` が使えるようにした（mpを引いてhpを増やす．最大値は超えない）．
ステータス表示関数をオーバーライトしてmpも表示するように変更．

In [244]:
class Hero(Character):
    def __init__(self, name, hp=200, mp=100, strength=30, magic=40):
        super().__init__(name, hp, strength)
        self.mp = mp
        self.magic = magic

    def magic_heal(self):
        self.mp -= 10
        print(self.name+'はかいふくまほうをとなえた.\nHPが'+str(self.magic*2)+'かいふくした.')
        self.hp += self.magic * 2
        self.hp = min(self.hp, self.max_hp)

    def status(self):
        print('#名前:', self.name, '\t#HP:', self.hp, '\t#MP:', self.mp)

## モンスタークラス

インスタンス化するときにモンスターの出現を知らせる処理を初期化メソッドに加筆．

In [245]:
class Monster(Character):
    def __init__(self, name, hp=100, strength=10):
        super().__init__(name, hp, strength)
        print(self.name+'があらわれた!')

## こんな感じで遊べます．

In [246]:
hero = Hero('勇者')
monsterA = Monster('スライム', hp=30, strength=10)
monsterB = Monster('スライムベス', hp=40, strength=20)

スライムがあらわれた!
スライムベスがあらわれた!


In [247]:
hero.attack(monsterA)

勇者のこうげき!
スライム は ひらりとみをかわした.


In [248]:
monsterA.attack(hero)

スライムのかいしんのいちげき!!!
勇者 は ひらりとみをかわした.


In [249]:
monsterB.attack(hero)

スライムベスのこうげき!
勇者 は ひらりとみをかわした.


In [250]:
hero.status()

#名前: 勇者 	#HP: 200 	#MP: 100


## 魔王と戦おう．

`command` の値により条件分岐．1なら攻撃，2なら回復，3ならループから抜ける（それ以外は `continue` で聞き直し）．
monsterのhpが0以下なら勝利，heroのhpが0以下なら敗北でループから抜ける．

In [251]:
hero = Hero('勇者', hp=200, mp=100, strength=30, magic=40)
monster = Monster('魔王', hp=300, strength=40)

while(True):
    hero.status()
    print('1-たたかう 2-かいふくじゅもん 3-にげる')
    command = input('コマンド?>')
    if command == '1':
        hero.attack(monster)
    elif command == '2':
        hero.magic_heal()
    elif command == '3':
        print(hero.name+'はにげだした.')
        break
    else:
        continue

    if monster.hp <= 0:
        print(monster.name+'をやっつけた.')
        break

    print()
    monster.attack(hero)

    if hero.hp <= 0:
        print(hero.name + 'はやられてしまった.')
        break
    print()

魔王があらわれた!
#名前: 勇者 	#HP: 200 	#MP: 100
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>1
勇者のこうげき!
魔王 は 30 のダメージ!

魔王のかいしんのいちげき!!!
勇者 は 80.0 のダメージ!

#名前: 勇者 	#HP: 120.0 	#MP: 100
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>1
勇者のかいしんのいちげき!!!
魔王 は 60.0 のダメージ!

魔王のかいしんのいちげき!!!
勇者 は 80.0 のダメージ!

#名前: 勇者 	#HP: 40.0 	#MP: 100
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>2
勇者はかいふくまほうをとなえた.
HPが80かいふくした.

魔王のこうげき!
勇者 は 40 のダメージ!

#名前: 勇者 	#HP: 80.0 	#MP: 90
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>2
勇者はかいふくまほうをとなえた.
HPが80かいふくした.

魔王のこうげき!
勇者 は ひらりとみをかわした.

#名前: 勇者 	#HP: 160.0 	#MP: 80
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>1
勇者のかいしんのいちげき!!!
魔王 は 60.0 のダメージ!

魔王のこうげき!
勇者 は 40 のダメージ!

#名前: 勇者 	#HP: 120.0 	#MP: 80
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>1
勇者のかいしんのいちげき!!!
魔王 は 60.0 のダメージ!

魔王のかいしんのいちげき!!!
勇者 は 80.0 のダメージ!

#名前: 勇者 	#HP: 40.0 	#MP: 80
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>2
勇者はかいふくまほうをとなえた.
HPが80かいふくした.

魔王のこうげき!
勇者 は 40 のダメージ!

#名前: 勇者 	#HP: 80.0 	#MP: 70
1-たたかう 2-かいふくじゅもん 3-にげる
コマンド?>2
勇者はかいふくまほうをとなえた.
HPが80かいふくした.

魔王のこうげき!
勇者 は 40 のダメージ!

#名前: 勇者 	#HP: 120.0 	#MP:

## 課題14

> store クラスを改良し、お客となるCustomerクラスとやり取りをするようにしてみましょう
>
> Customerクラスは次のような仕様を満たすこと．
> - 所有物の変数と所持金の変数がある
> - 所持金が足りるならTrue, 足りなければFalseを返すメソッドを持つ
> - 所持金を表示するメソッドを持つ
> - storeで買い物をするとcustomerクラスの変数と所持金が変化する
> - storeクラスの所持金残高によって買えない場合もある．
> - （お釣りの計算や，支払い金額の入力処理は消す）
>
> メインループの例
> ```python
> store = Store()
> store.set_products({"apple":100, "lemon":150, "grape":200})
> customer = Customer(money=1000)
>
> while(True):
>     customer.show_money()
>     mode = store.mode_select()
>     if mode == "admin":
>         store.admin_mode()
>     elif mode == "customer":
>         store.customer_mode(customer)
> ```

### 解答例

- `Customer` クラス : 所有物 `self.belongings`（辞書 {商品名: 個数}）と所持金 `self.money` を持ち，`can_pay(amount)`，`show_money()`，`pay(amount)`，`receive(item, count)` のメソッドを持つ．
- `Store` クラスは課題13のものを継承し，`customer_mode()` をお客さんとやり取りするように書き換える（支払い金額の入力とお釣りの処理は無くし，所持金が足りなければ買えない）．

In [252]:
class Customer:
    def __init__(self, money=1000):
        self.money = money          # 所持金
        self.belongings = {}        # 所有物 {商品名: 個数}

    def can_pay(self, amount):
        """所持金が足りるなら True, 足りなければ False を返す."""
        return self.money >= amount

    def show_money(self):
        """所持金を表示する."""
        print('[お客さん] 所持金:', self.money, '円  所有物:', self.belongings)

    def pay(self, amount):
        """支払う (所持金が減る)."""
        self.money -= amount

    def receive(self, item, count):
        """商品を受け取る (所有物が増える)."""
        if item in self.belongings:
            self.belongings[item] += count
        else:
            self.belongings[item] = count


class Store2(Store):
    """課題13のStoreクラスを継承し, Customerクラスとやり取りするように改良したもの."""

    def customer_mode(self, customer):
        """購入モード. お客さん(customer)に代金を払ってもらい, 商品を渡す."""
        self.show_products()
        self.select_items()
        total = self.calc_total()
        if total == 0:
            print('またのお越しをお待ちしております.')
            return

        print('合計', total, '円です.')
        if customer.can_pay(total):
            customer.pay(total)
            for item in self.cart:
                customer.receive(item, self.cart[item])
            print(total, '円いただきました. ありがとうございました.')
        else:
            print('所持金が', customer.money, '円なので足りません. 購入できません.')

In [253]:
store = Store2()
store.set_products({"apple": 100, "lemon": 150, "grape": 200})
customer = Customer(money=1000)

while(True):
    customer.show_money()
    mode = store.mode_select()
    if mode == "admin":
        store.admin_mode()
    elif mode == "customer":
        store.customer_mode(customer)
    elif mode == "quit":
        print('終了します.')
        break

[お客さん] 所持金: 1000 円  所有物: {}
あなたは管理者ですか? (y/n, 終了する場合は q): n
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
何を買いますか? (やめる場合は q): apple
何個買いますか?: 3
apple を 3 個ですね.
何を買いますか? (やめる場合は q): grape
何個買いますか?: 2
grape を 2 個ですね.
何を買いますか? (やめる場合は q): q
合計 700 円です.
700 円いただきました. ありがとうございました.
[お客さん] 所持金: 300 円  所有物: {'apple': 3, 'grape': 2}
あなたは管理者ですか? (y/n, 終了する場合は q): y
パスワードを入力してください (やめる場合は q): denki
管理モードに入ります.
追加する商品の名前: melon
その商品の金額: 500
melon を 500 円で追加しました.
[お客さん] 所持金: 300 円  所有物: {'apple': 3, 'grape': 2}
あなたは管理者ですか? (y/n, 終了する場合は q): n
いらっしゃいませ
商品リスト:
   apple : 100 円
   lemon : 150 円
   grape : 200 円
   melon : 500 円
何を買いますか? (やめる場合は q): melon
何個買いますか?: 1
melon を 1 個ですね.
何を買いますか? (やめる場合は q): q
合計 500 円です.
所持金が 300 円なので足りません. 購入できません.
[お客さん] 所持金: 300 円  所有物: {'apple': 3, 'grape': 2}
あなたは管理者ですか? (y/n, 終了する場合は q): q
終了します.


## 最強のライブラリ numpy

多次元配列処理用ライブラリ．`import numpy as np` として使うのが慣例．例えば行列 $A$ の逆行列を求めるのはたった2行で終わり．

In [254]:
import numpy as np

In [255]:
A = np.array([[1, -2, 0], [1, 1, -1], [-5, 5, 2]])
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 7.  4.  2.]
 [ 3.  2.  1.]
 [10.  5.  3.]]


## numpy は 早い！

numpyはメモリ管理を工夫し，裏でC言語などで高速に演算できるよう作られている．300行300列の行列の積を，for文で作った場合とnumpyで計算した場合でかかる時間を比べてみよう．

In [256]:
np.random.seed(0)
N = 300
A = np.array(np.random.randint(0, 3, (N, N)))
B = np.array(np.random.randint(0, 3, (N, N)))

In [257]:
import time
start = time.time()

C = np.array([[0] * N for x in range(N)])
for iii in range(N):
    for jjj in range(N):
        for kkk in range(N):
            C[iii][jjj] += A[iii][kkk] * B[kkk][jjj]
print(C)

print('for文でかかった時間:', time.time() - start, '秒')

[[332 277 273 ... 297 278 285]
 [318 278 273 ... 290 273 289]
 [338 327 286 ... 290 296 317]
 ...
 [319 288 254 ... 276 297 276]
 [325 318 298 ... 277 310 302]
 [348 330 300 ... 311 335 293]]
for文でかかった時間: 28.64049530029297 秒


In [258]:
start = time.time()

C = np.dot(A, B)
print(C)

print('numpyでかかった時間:', time.time() - start, '秒')

[[332 277 273 ... 297 278 285]
 [318 278 273 ... 290 273 289]
 [338 327 286 ... 290 296 317]
 ...
 [319 288 254 ... 276 297 276]
 [325 318 298 ... 277 310 302]
 [348 330 300 ... 311 335 293]]
numpyでかかった時間: 0.030553102493286133 秒


## numpyで配列を作る

`np.array()` にリストを渡す．ndarray型のオブジェクトができる．

- `ndim` : 配列の次元数
- `size` : 配列要素の総数
- `shape` : 配列の形状

In [259]:
A = np.array([2, 4, 6, 8])

In [260]:
print(A)
print(A.ndim)
print(A.size)
print(A.shape)

[2 4 6 8]
1
4
(4,)


## numpyで二次元配列を作る

こんな感じの行列として捉えることができる．

In [261]:
B = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [262]:
print(B)
print(B.ndim)
print(B.size)
print(B.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
9
(3, 3)


## arange()関数で配列生成

スマートに配列を生成するには `np.arange()` を使う．少数だっていけちゃう．

In [263]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [264]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [265]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [266]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

## さらに色々な配列生成方法

- `np.zeros()` : 全てが0の配列を作る
- `np.ones()` : 全てが1の配列を作る
- `np.random.random()` : 0.0〜1.0のランダムな値で配列を作る

他にもたくさんあります．

In [267]:
np.zeros(3)

array([0., 0., 0.])

In [268]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [269]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [270]:
np.random.random((3, 2))

array([[0.45858924, 0.83413556],
       [0.35342364, 0.72360387],
       [0.44590559, 0.64258752]])

## numpyの表示桁数を変更する

`np.set_printoptions(precision=〇)` で表示桁数を変更できる！（〇は桁数を表す整数）あくまでも表示桁数なので計算が丸められたりはしない．

In [271]:
np.set_printoptions(precision=3)

In [272]:
np.random.random((3, 2))

array([[0.035, 0.96 ],
       [0.71 , 0.925],
       [0.706, 0.178]])

## reshape()で形状を変える

- `<ndarray型>.reshape(〇, ●)` : 〇行●列の形に変換する **メソッド**
- `np.reshape(△, (〇, ●))` : 行列△を〇行●列の形に変換する **関数**

メソッドと関数で同じ処理ができることも多いです．

In [273]:
A = np.arange(12)
print(A)
A = A.reshape(2,6)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [274]:
A = np.reshape(A, (3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## numpyのインデキシング

一次元配列はリストと同じように参照できる．二次元以上の配列は `[〇][●]` ではなく `[〇, ●]` としても良いことに注意．

In [275]:
A = np.array([6, 3, 1, 8, 0, 7])
print(A)
print(A[3])
print(A[-1])

[6 3 1 8 0 7]
8
7


In [276]:
A = np.arange(12).reshape((3,4))
print(A)
print(A[1][2])
print(A[1, 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
6


## numpyのスライシング

`A[〇, ●]` の〇に行，●に列の範囲を指定する．

In [277]:
A = np.arange(15).reshape((3,5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [278]:
A[2,:]

array([10, 11, 12, 13, 14])

In [279]:
A[1, 3:]

array([8, 9])

In [280]:
A[:1, 2:]

array([[2, 3, 4]])

In [281]:
A[:,1]

array([ 1,  6, 11])

In [282]:
A[-1,:3]

array([10, 11, 12])

## ndarrayとスカラーの計算

numpy配列とスカラー値を計算すると自動的に全ての要素に適用される．

In [283]:
A = np.arange(6)
A = A.reshape(2,3)
print(A)

[[0 1 2]
 [3 4 5]]


In [284]:
A + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [285]:
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [286]:
A + 3.0

array([[3., 4., 5.],
       [6., 7., 8.]])

In [287]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

## ブロードキャスティング・配列同士の計算

numpyにはブロードキャスティングという最強機能が付いている．形の違う配列同士でも，小さい方の配列を自動的に引き伸ばして（ブロードキャスティングした上で）対応する要素同士が計算される．

In [288]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(1,4)
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [289]:
A + B

array([[2, 4, 6],
       [5, 7, 9]])

In [290]:
A * B

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [291]:
A / B

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

## ブロードキャスティングできないケース

こんな場合はブロードキャスティングすることができず，エラーになる．

In [292]:
A = np.arange(6).reshape(2,3)
print(A)
A + np.array([1, 2])          # 2行3列 + 要素数2 → 列の数が合わない

[[0 1 2]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [293]:
A + np.array([[5], [6], [7]])   # 2行3列 + 3行1列 → 行の数が合わない

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

## numpyで線形代数！

行列の掛け算は `np.dot(A, B)`，`A.dot(B)`，`A @ B` のどれでも計算できる．

In [294]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

In [295]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [296]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [297]:
A @ B

array([[19, 22],
       [43, 50]])

ベクトルの内積は `np.inner(〇, ●)`，外積は `np.cross(〇, ●)`．

In [298]:
A = np.array([2, 1, 0])
B = np.array([1, 3, 0])

In [299]:
np.inner(A, B)

np.int64(5)

In [300]:
np.cross(A, B)

array([0, 0, 5])

固有値，固有ベクトルの計算は `np.linalg.eig()`（引数行列の固有値と固有ベクトルを返す）．

$A\boldsymbol{x} = \lambda\boldsymbol{x}$ の $\lambda$ が固有値，$\boldsymbol{x}$ が固有ベクトル．固有ベクトルは **列** ごとに並んでいることに注意．

In [301]:
A = np.array([[1, 3], [4, 2]])
l, x = np.linalg.eig(A)
print(l)
print(x)

[-2.  5.]
[[-0.707 -0.6  ]
 [ 0.707 -0.8  ]]


行列式の計算は `np.linalg.det()`．

In [302]:
A = np.array([[2, 5], [1, 3]])
np.linalg.det(A)

np.float64(1.0)

In [303]:
A = np.array([[2, 5, 3, 7],
              [1, 4, 5, 3],
              [8, 2, 4, 9],
              [2, 1, 4, 2]])
np.linalg.det(A)

np.float64(128.99999999999997)